"""
WebGuard: A Comprehensive Fuzzer for Web Application Security
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/13PhvS9RucBMO-DViNrLIu1aaYttGWiT0
"""

import streamlit as st
import shutil
import pickle
import pandas as pd
from extract_features import ExtractFeatures
from PIL import Image
from io import BytesIO
import requests
import dns.resolver
from urllib.parse import urljoin
import streamlit.components.v1 as components
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import base64
from st_aggrid import AgGrid, GridUpdateMode, JsCode
from st_aggrid.grid_options_builder import GridOptionsBuilder
from streamlit_option_menu import option_menu
import json
import os
from groq import Groq
import time
import sys
from streamlit.components.v1 import html
from agstyler import PINLEFT, draw_grid, JsCode
import re
import random
import urllib.parse


from streamlit.components.v1 import html

sys.path.append(os.path.join(os.path.dirname(__file__), 'Mitre-Att&ck/src'))
sys.path.append(os.path.join(os.path.dirname(__file__), 'rapid_scan'))
sys.path.append(os.path.join(os.path.dirname(__file__), 'fuzzer-sih'))
sys.path.append(os.path.join(os.path.dirname(__file__), 'proxycheck'))

from rapid_scan.streamlit_json_cli import perform_vulnerability_scan
# from injectx_streamlit_run import run_injectx_scan
from threats2MitreRun import processThreatsScenario
from proxycheck import get_ip_details
from config import fuzz

st.set_page_config(page_title="WebGuard", layout="wide")
# Load images
image2 = Image.open('webguard.png')
image = Image.open('sihlogo.jpg') 
col1, col2, col3 = st.columns([1,4.5,2])

  # Function to encode image to base64
def get_base64_encoded_image(image_path):
        with open(image_path, "rb") as img_file:
            return base64.b64encode(img_file.read()).decode()

sihlogo_base64 = get_base64_encoded_image("sihlogo.jpg")
webguard_base64 = get_base64_encoded_image("webguard.png")

def get_svg_content(svg_name):
    try:
        with open(f"{svg_name}.svg", "r") as file:
            return file.read()
    except FileNotFoundError:
        return ""
with col3:
    redirect_url = "https://github.com/iamaastharawat/CustomRules-VidhyaDhaar.git"

    # Encode the image to base64
    extension_button_new_base64 = get_svg_content("button-new")

    # Create a button with an image background
    st.markdown(f"""
        <style>
        .button {{
            background-color: #3c3c3c;
            height: 45px;  /* Adjust height */
            border: none;
            border-radius: 10px;
            cursor: pointer;
            color: white;
            padding-left: 10px;
            padding-right: 10px;
            font-weight: semibold;
            display: inline-block;
        }}
        .button:hover {{
            background-color: #4c4c4c;
        }}
        </style>
        <a href="{redirect_url}" target="_blank">
            <button class="button">{extension_button_new_base64} Try our Early Code Tester</button>
        </a>
    """, unsafe_allow_html=True)

def initialize_dnsdumpster():
    try:
        api_key = "dbdbdd5b1a6707cea92ae17e01764588ffc4ca69bf3e9050f2384b02021f5cca"
        return api_key
    except Exception as e:
        st.error(f"Failed to initialize DNSDumpster: {str(e)}")
        return None


def query_dnsdumpster(domain):
    api_key = initialize_dnsdumpster()
    if not api_key:
        return None
    
    headers = {
        'X-API-Key': api_key
    }
    
    try:
        response = requests.get(
            f'https://api.dnsdumpster.com/domain/{domain}',
            headers=headers
        )
        return response.json() if response.status_code == 200 else None
    except Exception as e:
        st.error(f"DNSDumpster API error: {str(e)}")
        return None
    

def analyze_dns_data(dns_data):
    findings = {
        'subdomains': set(),
        'ip_addresses': set(),
        'potential_apis': set()
    }
    
    if not dns_data:
        return findings
    
    # Extract A records
    for record in dns_data.get('a', []):
        findings['subdomains'].add(record['host'])
        for ip_info in record['ips']:
            findings['ip_addresses'].add(ip_info['ip'])
            # Check for API endpoints in banners
            if 'banners' in ip_info:
                for protocol in ['http', 'https']:
                    if protocol in ip_info['banners']:
                        banner = ip_info['banners'][protocol]
                        if 'api' in banner.get('title', '').lower():
                            findings['potential_apis'].add(f"{protocol}://{ip_info['ip']}")

    # Extract CNAME records
    for record in dns_data.get('cname', []):
        findings['subdomains'].add(record['host'])
        
    return findings


def table_vulnerability():
    try:
        # st.title("Security Scan Results")


        # Convert to DataFrame
        df = pd.DataFrame(scan_results)

        if not df.empty:

            st.markdown('''
                        <style>
                        [data-testid="stMetric"] > div {
                            color: #00abd7 !important;
                            padding-bottom:20px;
                        }
                        </style>
                        ''',unsafe_allow_html=True)

            # Create a single JsCode object for all threat level conditions
            threat_level_style = JsCode("""
                function(params) {
                    if (params.value === 'High') {
                        return {'backgroundColor': '#E1ABAB', 'font-style': 'italic' , 'box-shadow': 'inset 0 0 20px 10px #F47A7A', 'text-align' : 'center', 'border-radius' : '10px'};
            } else if (params.value === 'Medium') {
                return {'backgroundColor': '#FCDDA9', 'font-style': 'italic', 'box-shadow': 'inset 0 0 20px 10px #E5C082', 'text-align' : 'center', 'border-radius' : '10px'};
            } else if (params.value === 'Low') {
                return {'backgroundColor': '#CDE1AB', 'font-style': 'italic', 'box-shadow': 'inset 0 0 20px 10px #A8E594', 'text-align' : 'center', 'border-radius' : '10px'};
            } else if (params.value === 'Safe') {
                return {'backgroundColor': '#FCEFA9', 'font-style': 'italic', 'box-shadow': 'inset 0 0 20px 10px #E7D574', 'text-align' : 'center', 'border-radius' : '10px'};
            } 
        }
    """)
            status_style = JsCode("""
                function(params) {
                    if (params.value === 'Completed') {
                        return {'color': '#6AD652'};
                    } else if (params.value === 'Skipped') {
                        return {'color': '#E1ABAB'};
                    }
                }
            """)

            bg_color = JsCode("""
                function(params) {
                    if (params.value != '') {
                        return {'backgroundColor': 'transparent'};
                    }
                }
            """)


            # Define the formatter for the table
            formatter = {
                'Test Name': ('Test Name', PINLEFT),
                'Status': (
                    'Status', {
                                'width': 120,
                                'cellStyle' : status_style
                    }),
                'Time Taken': ('Time Taken', {'width': 100}),
                'Threat Level': (
                    'Threat Level',
                    {
                        'width': 50,
                        'cellStyle': threat_level_style
                    }
                )

            }

            # Apply the table with AgStyler
            grid_response = draw_grid( 
                df = df,
                formatter=formatter, 
                fit_columns=True, 
                # selection='multiple', 
                use_checkbox=True, 
                max_height=700,
            )


            if grid_response['selected_rows']:
                st.subheader("Selected Vulnerabilities")
                selected_df = pd.DataFrame(grid_response['selected_rows'])
                st.dataframe(
                    selected_df,
                    column_config={
                        "Test Name": st.column_config.TextColumn("Test Name", width="medium"),
                        "Status": st.column_config.TextColumn("Status", width="small"),
                        "Time Taken": st.column_config.TextColumn("Time Taken", width="small"),
                        "Threat Level": st.column_config.TextColumn("Threat Level", width="small"),
                    },
                    hide_index=True,
        )

          
            st.markdown('''
                        <style>
                        [data-testid="stMetric"] > div {
                            color: #00abd7 !important;
                            padding-bottom:20px;
                        }
                        </style>
                        ''',unsafe_allow_html=True)

    

            # Display summary statistics
            st.subheader("Threat Level Summary")
            col1, col2, col3, col4, col5= st.columns(5)
        
            with col1:
                st.metric("Total Tests", len(df))
            with col2:
                completed_tests = len(df[df['Status'] == 'Completed'])
                st.metric("Completed Tests", completed_tests)
            with col3:
                high_threats = len(df[df['Threat Level'] == 'High'])
                st.metric("High Threats", high_threats)
            with col4:
                medium_threats = len(df[df['Threat Level'] == 'Medium'])
                st.metric("Medium Threats", medium_threats)
            with col5:
                low_threats = len(df[df['Threat Level'] == 'Low'])
                st.metric("Low Threats", low_threats)
            
            st.subheader("Threat Distribution")
            threat_counts = df['Threat Level'].value_counts()
            st.bar_chart(threat_counts)

    except Exception as e:
        st.error(f"An error occurred: {str(e)}")
        st.info("Please make sure all required dependencies are installed.")


    
red_svg = get_svg_content("red")
green_svg = get_svg_content("green")
yellow_svg = get_svg_content("yellow")
statusg_svg = get_svg_content("statusg")
statusy_svg = get_svg_content("statusy")
statusr_svg = get_svg_content("statusr")





st.markdown("""
    <style>
      [data-testid="stAppViewContainer"] {
        overflow-x: hidden;
        max-width: 100vw;
    }
       ::-webkit-scrollbar {
        display: none;
    }

    /* Also prevent overflow on the main content */
    .main {
        overflow-x: hidden;
    }
     [data-testid="stSidebar"][aria-expanded="false"] {
        margin-left: -100px;
        width: 0px;
    }

    /* Sidebar default expanded state */
    [data-testid="stSidebar"][aria-expanded="true"] {
        margin-left: 0;
        width: 100px;
    }

    /* Ensure all transitions are smooth */
    [data-testid="stSidebar"] {
        transition: margin 0.3s, width 0.3s;
    }
    </style>
""", unsafe_allow_html=True)


   # Get the base64 encoded background image
try:
    bg_image = get_base64_encoded_image("bgchatbot.png")
    
    page_bg_color = f"""
    <style>
    [data-testid="stAppViewContainer"] {{
        background-image: url("data:image/png;base64,{bg_image}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        z-index: 100;
        margin-left: 0;
        margin:auto; !important
    }}
    [data-testid="stHeader"] {{
        background-image: url("data:image/png;base64,{bg_image}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        z-index: 100;
    }}

     [data-testid="stSidebar"] {{
            background-color: #343434;
            max-width: 100px;
            padding: 0;
            padding-right: -100px;
        }}
    [data-testid= "stCustomComponentV1"]{{
            background-color: transparent !important;
    }}


    </style>"""
    


    # Inject the CSS into the app
    st.markdown(page_bg_color, unsafe_allow_html=True)

except FileNotFoundError:
    st.error("Could not find bg.png - please check the file path")



st.markdown("""
            <style>
            .vsc-initialized{
                background-color:#343434;
                width: 100px !important;
                }
            
            [id="app"] > div > div > * {
                width: 100px !important;
            }

            [data-testid="stSidebarUserContent"] {
                margin-left: 50px !important;
                padding: 0 !important;
            }
            </style>

            """, unsafe_allow_html = True)
with col1:
    # with st.sidebar:
        # Replace file-based image with base64 image
        st.markdown(f"""
            <img src="data:image/png;base64,{sihlogo_base64}" 
                 width="110px"
                 style="margin-left: 0px; margin-right:0px;margin-top : -10px; display: block;">
            """, unsafe_allow_html=True)

        # selected = option_menu(
        #         menu_title = None,
        #         options = ["Vulnerability Check", "MITRE Chatbot", "About"],
        #         icons =["speedometer","chat-left-text", "journal-plus"],
        #         default_index = 0,
        #         # orientation = "horizontal",
        #         styles={
        #         "container": {"margin-bottom": "15px", "margin-left": "0", "background-color": "#343434", "border-radius": "0px", "border":"10px solid #343434"},
        #         "icon": {"color": "#00ABD7", "font-size": "22px", "align-items":"right",}, 
        #         "nav-link": {"font-size": "0px","color":"transparent", "align-items": "center", "margin-left":"0px", "--hover-color": "transparent", "background-color": "transparent", "width":"55px","padding-right":"0px","border-radius":"45px"},
        #         "nav-link-selected": {"border": "0px solid white","border-radius":"45px 0px 0px 45px", "background-color":"#E7F8FE", "transition":"width 1s ease-in-out, background-color 1s ease-in-out, border-radius 1s ease-in-out", "width": "200px", "transform-origin": "left"},
        #     }
        # )

        
# if selected == "Vulnerability Check":

    # with col2:
    #     st.markdown('<div class="image-container">', unsafe_allow_html=True)
    #     st.image(image, output_format="auto")
    #     st.markdown('</div>', unsafe_allow_html=True)

    # with col3:
    #     st.markdown('<div class="image-containers">', unsafe_allow_html=True)
    #     st.image(image2, output_format="auto")
    #     st.markdown('</div>', unsafe_allow_html=True)


html_code = '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="sihlogo.ico">
    <title>WebGuard</title>
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
    @import url('https://fonts.cdnfonts.com/css/switzer');
        /* Reset some default styles */
        * {
        max-width: 100vw;
        box-sizing: border-box;
        margin: 0;
        padding: 0;
        }
        
        .stMain{
        max-width: 100vw;
        }

        body {
        font-family: 'Inter', sans-serif;
        background-color: #000;
        color: #000;
        }

        .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 2rem;
        }

        header {
        text-align: center;
        margin-bottom: 0;
        }


        h1{
            color: #000;
            font-family: 'Switzer', sans-serif;
            font-weight: 400;
            font-size: 2.5rem;
        

        }

        /* Existing CSS styles */
    
        
        /* Add these new styles for the URL input text area */
        [data-testid="stTextArea"] label {
            font-size: 18px !important;
            font-weight: bold !important;
            color: #A3B8EF !important;
        }
        
        [data-testid="stTextArea"] textarea::placeholder {
            color: black !important;
        }
        
        [data-testid="stTextArea"] textarea {
            color: #28B7DA !important;
            caret-color: #28B7DA !important;
            font-size: 16px !important;
            padding-left: 40px !important;
            padding-top: 3vh !important;
            max-height: 40px !important;
            width: 70vw !important;
            margin: auto !important;
            background-color: rgba(65, 175, 255, 0.17); !important;
            background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="%23000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg>') !important;
            background-repeat: no-repeat !important;
            background-position: 10px center !important;
            border: 8px solid #A3B8EF !important;
            border-color: #A3B8EF !important;
            border-radius: 90px !important;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1) !important;
            font-family: 'Inter', sans-serif;
        }
        
        [data-testid="stTextArea"] textarea:focus {
            border-color: #00ABD7 !important;
            outline: none !important;
            color: #000 !important;
        }

        .st-c0 {
            min-height: 70px;
            margin-bottom: 10px !important;
        }

        h2 {
            font-family: 'Inter', sans-serif;
            margin-top: -3vh;
        }

        h3{
            font-family: 'Inter', sans-serif;
            font-size: 1rem;
            text-align: center;
            font-weight: 600;
            color: #000;
        }

        .heading {
            margin-top: -20vh;
            width: 60vw;
            text-align: center;
            margin: auto;
        }


        .animated-text span{
            position: relative;
        }

        .animated-text span::before{
            content: "Your first step to a safer web";
            animation: words 15s infinite;
        }

        .animated-text span::after{
            content: "";
            position: absolute;
            width: calc(100% + 20px);
            height: 110%;
            background-color: #F5FFFE;
            border-left: 3px solid #00ABD7;
            right: -5px;
            animation: cursor 0.75s infinite, typing 15s steps(45) infinite;
        }

        @keyframes cursor {
            to{
                border-left: 2px solid #ff7f5000;
            }
        }

        @keyframes words {
            0%,20%{
                content:"Detect vulnerabilities in an instant";
                transition:0.5s ease-in-out;

            }
            27%,55%{
                content:"Brute force exceptions and authentication";
                transition:0.5s ease-in-out;
            }
            75%,90%{
                content: "Your first step to a safer web";
                transition:0.5s ease-in-out;
            }
        }

        @keyframes typing {
            10%,30%,50%,70%,90%{
                width: 0;
            }
            20%,25%,40%,60%,65%,80%,85%{
                width: calc(100% + 5px);
            }
        }
        .animated-text span{
            color: #000;
            font-family: 'Switzer', sans-serif;
            font-weight: 400;
            font-size: 2.2rem;
        
        }
        
    </style>
    </head>
    <body>
    <div class="heading" style="padding-top: 10vh;">
    <div class = "animated-text"><span></span></div>
    <h2 style="color: #3B5574; display: inline-block;font-style: italic; font-weight: 400; font-size: 1.75rem; padding-top: -3vh;">Test smarter, secure stronger.</h2>
    </div>
    </body>
    </html>'''

st.markdown(html_code, unsafe_allow_html=True)

# Function to encode image to base64
def get_base64_encoded_image(image_path):
    with open(image_path, "rb") as img_file:
        return base64.b64encode(img_file.read()).decode()

# Get the base64 encoded background image
try:
    bg_image = get_base64_encoded_image("bg.png")
except FileNotFoundError:
    st.error("Could not find bg.png - please check the file path")
    
page_bg_color = f"""
        <style>
        [data-testid="stAppViewContainer"] {{
            background-image: url("data:image/png;base64,{bg_image}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            z-index: 100;
        }}
        [data-testid="stHeader"] {{
        background-image: url("data:image/png;base64,{bg_image}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            z-index: 100;
        }}
        [data-testid="stSidebar"] {{
            background-color: #343434;
            width: 100px !important;
            padding: 0 !important;
        }}
        .stTextInput > div > div > input {{
            background-color : rgba(65, 175, 255, 0.17);
            border: 4px solid #A3B8EF !important;
            border-radius: 90px;
            color: black !important;
        }}

        /* Make sure list items are also black */
        li {{
            color: black !important;
        }}

        [data-testid="stTextArea"] {{
            display: flex;
        }}
        
        [data-testid="stTextArea"] > div {{
            background-color: transparent !important;
            width: 600px;
            margin: auto;
            border: none !important;
        }}
        
        [data-testid="stTextArea"] > div > div {{
            background-color: transparent !important;
            border: none !important;
        }}

        /* Style the text area */
        .stTextArea textarea {{
            background-color: rgba(65, 175, 255, 0.17);
            border: 4px solid #00ABD7 !important;
            border-radius: 15px;
            color: black !important;
        }}
        /* Ensure all regular text and markdown text is black */
        p, .markdown-text-container {{
            color: black;
        }}
        /* Remove black background from text area container */
        .stTextArea {{
            background-color: transparent !important;
        }}
        
        /* Remove any additional container styling */
        .element-container {{
            background-color: transparent !important;
        }}

        /* Remove default streamlit container backgrounds */
        [data-testid="stForm"] {{
            background-color: transparent !important;
        }}

        .checktest{{
            display: flex;
            gap: 10px;
            text-align:left;
            font-weight:400;
            font-size: 14px;
            margin:0;
            color: black;
        }}
        </style>
        """


    # Inject the CSS into the app
st.markdown(page_bg_color, unsafe_allow_html=True)




# Caching the phishing URL detection model
@st.cache_resource
def get_model():
    """
    This function initializes and returns a sample machine learning model for parameter fuzzing.
    Replace this with your actual model loading logic.
    """
    try:
        with open('phishing_url_detector.pkl', 'rb') as pickle_model:
            model = pickle.load(pickle_model)
        st.success("Model loaded successfully for parameter fuzzing...")
    except FileNotFoundError:
        st.error("Model file not found! Please ensure the 'parameter_fuzzing_model.pkl' exists.")
        model = None
    return model

# Directory enumeration and file brute-forcing
COMMON_DIRECTORIES = ["admin", "login", "test", "backup"]
COMMON_EXTENSIONS = [".php", ".html", ".asp", ".js"]
COMMON_SUBDOMAINS = ["www", "api", "mail", "ftp"]

# Function to check if a URL returns a 404 error
def check_404(url):
    try:
        response = requests.head(url, timeout=10)  # Use HEAD request for faster checking
        return response.status_code == 404
    except requests.RequestException:
        return False

# Function to brute force valid URLs (directories and files)
def brute_force_url(base_url):
    found_urls = []
    for directory in COMMON_DIRECTORIES:
        for ext in COMMON_EXTENSIONS:
            full_url = urljoin(base_url, f"{directory}{ext}")
            if not check_404(full_url):
                found_urls.append(full_url)
    return found_urls

# Function to brute force Virtual Hosts (subdomains)
def fuzz_virtual_hosts(domain):
    found_vhosts = []
    for subdomain in COMMON_SUBDOMAINS:
        vhost = f"{subdomain}.{domain}"
        try:
            response = requests.get(f"http://{vhost}", timeout=10)
            if response.status_code == 200:
                found_vhosts.append(vhost)
        except requests.RequestException:
            continue
    return found_vhosts

# API endpoint fuzzing
API_ENDPOINTS = ["/api/v1/", "/api/v2/", "/api/user/", "/api/admin/"]
def test_api_endpoints(base_url):
    found_endpoints = []
    for endpoint in API_ENDPOINTS:
        full_url = urljoin(base_url, endpoint)
        try:
            response = requests.get(full_url, timeout=10)
            if response.status_code == 200:
                found_endpoints.append(full_url)
        except requests.RequestException:
            continue
    return found_endpoints

# URL parameter fuzzing
def fuzz_parameters(base_url):
    """
    Perform parameter fuzzing using a sample model.
    """
    model = get_model()
    if model is None:
        st.warning("Model not loaded. Unable to perform parameter fuzzing.")
        return pd.DataFrame()

    payloads = ["' OR 1=1 --", "<script>alert('XSS')</script>", "../etc/passwd"]
    found_vulnerabilities = []

    for payload in payloads:
        fuzzed_url = f"{base_url}?param={payload}"
        try:
            response = requests.get(fuzzed_url, timeout=10)
            if response.status_code == 200:
                prediction = model.predict([[payload]])  # Replace with actual input features for your model
                if prediction:
                    found_vulnerabilities.append({
                        "URL": fuzzed_url,
                        "Payload": payload,
                        "Prediction": "Vulnerable"
                    })
                else:
                    found_vulnerabilities.append({
                        "URL": fuzzed_url,
                        "Payload": payload,
                        "Prediction": "Safe"
                    })
        except requests.RequestException:
            continue

    return pd.DataFrame(found_vulnerabilities)


svg_btn = get_base64_encoded_image("submit.svg")

button_style = """
    <style>
    [data-testid="stFormSubmitButton"] > button {
        content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='9 18 15 12 9 6'%3E%3C/polyline%3E%3C/svg%3E");
        background-color: #9FADCC;
        color: white;
        padding: 16px 16px;
        font-size: 16px;
        border-radius: 45px;
        border: none;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }
    [data-testid="stFormSubmitButton"] > button:focus {
        background-color: #00ABD7;
    }

    [data-testid="stFormSubmitButton"]{
        position: relative;
        margin-left: 535px;
    
        bottom: 79px;
    
    }
    [data-testid="stForm"] {
        background-color: transparent !important;
        padding: 0 !important;
        margin: auto !important;
        display: flex;
        justify-content: center;
        border:none !important;
    }
    </style>
"""
# Inject the custom CSS
st.markdown(button_style, unsafe_allow_html=True)
# Subdomain brute force discovery
def discover_subdomains(domain):
    found_subdomains = []
    for subdomain in COMMON_SUBDOMAINS:
        try:
            resolved = dns.resolver.resolve(f"{subdomain}.{domain}", 'A')
            found_subdomains.append(f"{subdomain}.{domain}")
        except (dns.resolver.NXDOMAIN, dns.resolver.Timeout):
            continue
    return found_subdomains

# Variables for the results
statuscode = ""
predictmsg = ""
img = ""
features_dataframe = ""
grid_options = ""
displaysvg = ""
display_dataframe = ""
with st.form(key='url_form', clear_on_submit=True):
    # Input for URL
    input_url = st.text_area("", placeholder="Enter the URL to test for vulnerabilities")

    # Submit button inside the form
    submit_button = st.form_submit_button("  ")

# if (input_url or submit_button) and not input_url.startswith(('http://', 'https://')):
#     input_url = 'https://' + input_url

    
    # Extracts features from the URL and converts it into a dataframe

# with st.form(key='url_form', clear_on_submit=True):
#     # Input for URL
#     input_url = st.text_area("", placeholder="Enter the URL to test for vulnerabilities")

#     # Submit button inside the form
#     submit_button = st.form_submit_button("Run Scan")

# # if (input_url or submit_button) and not input_url.startswith(('http://', 'https://')):
# #     input_url = 'https://' + input_url





if submit_button and input_url.strip():
    try:
        parsed_url = urllib.parse.urlparse(input_url)
        domain = parsed_url.netloc if parsed_url.netloc else input_url.split('/')[0]
        screen, dnstable, iptable = st.columns([0.5, 0.5, 0.5])

        chrome_options = Options()
        chrome_options.add_argument('--headless')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--disable-dev-shm-usage')
        
        with webdriver.Chrome(service=webdriver.chrome.service.Service(ChromeDriverManager().install()), options=chrome_options) as driver:
            # Get the screenshot
            driver.get(input_url)
            screenshot = driver.get_screenshot_as_png()
            driver.quit()
                
        # Diwithsplay the screenshot
        with screen:
            img = Image.open(BytesIO(screenshot))

            st.image(img, caption='Grid Screenshot', use_column_width=True)

        with dnstable:
            st.markdown("<h3>DNS Enumeration</h3>", unsafe_allow_html=True)
            # findings = {
            #     'subdomains': [],
            #     'ip_addresses': []
            # }
            dns_data = query_dnsdumpster(domain)
            if dns_data:
                findings = analyze_dns_data(dns_data)
                
            if findings['subdomains']:
                st.write("📡 Discovered Subdomains:")
                for subdomain in findings['subdomains']:
                    st.write(f"- {subdomain}")
                    subdomain_new = subdomain


        with iptable:
            if findings['ip_addresses']:
                st.write("🌐 Associated IP Addresses:")
                for ip in findings['ip_addresses']:
                    st.write(f"- {ip}")
        
        st.info("Checking IP addresses for proxy usage...")
        for ip in findings['ip_addresses']:
            st.write(f"- {ip}")
            st.write(ip)
            st.write(get_ip_details(ip))

        st.info("Fuzzing the URL...")
        # scan_output, vulnerabilities = run_injectx_scan(input_url)
        # st.write(scan_output)
        fuzz_results = fuzz(input_url)
        delay = random.uniform(5, 15)
        time.sleep(delay)
        print("\nFuzzing Completed! Results:")
        for result in fuzz_results:
            st.markdown(result)

        st.info("Running vulnerability scan...")
        
        # Extract features
        # features_url = ExtractFeatures().url_to_features(url=input_url)
        # features_dataframe = pd.DataFrame.from_dict([features_url]).fillna(-1)
        
        # # Validate and format data
        # try:
        #     features_dataframe = features_dataframe.astype(int)
        # except Exception as e:
        #     st.error(f"Data type casting error: {e}")
        
        # Perform the scan
        scan_results, highest_threat_level = perform_vulnerability_scan(input_url)
        
        # # Validate if DataFrame is not empty and has the correct number of features
        # if not features_dataframe.empty and features_dataframe.shape[1] == 13:
        #     st.title("Vector Fuzzing Results")
            
        #     phishing_url_detector = get_model()
        #     prediction = phishing_url_detector.predict(features_dataframe.iloc[:, :13])
            
        #     # Generate prediction message
        #     if prediction == 1:
        #         predictmsg = '<div style="color:#B01E1E; font-weight:600;">Alert: Critical Vulnerabilities Detected</div>'
        #     elif prediction == 0:
        #         predictmsg = '<div style="color:#1EB035; font-weight:600;">No suspicious activities identified.</div>'
        #     else:
        #         predictmsg = '<div style="color:#FFD83C; font-weight:600;">Unknown prediction result.</div>'
            
        #     st.markdown(predictmsg, unsafe_allow_html=True)
            
        #     # Display formatted DataFrame
        #     st.dataframe(features_dataframe.T.reset_index(drop=False))
        # else:
        #     st.error("Data validation failed: Incorrect number of features.")
        
        # Screenshot functionality
        
        # st.info("Calculating Threat Level...")
        def parse_vulnerability_entries(text):
            """Parse the text file into separate vulnerability entries"""
            entries = []
            current_entry = {}
            lines = text.split('\n')
            
            for line in lines:
                if line.startswith('Test:'):
                    if current_entry:
                        entries.append(current_entry)
                    current_entry = {'Test': line[5:].strip()}
                elif line.startswith('Vulnerability Definition:'):
                    current_entry['Definition'] = line[24:].strip()
                elif line.startswith('Vulnerability Remediation:'):
                    current_entry['Remediation'] = line[25:].strip()
            
            if current_entry:
                entries.append(current_entry)
            
            return entries
        
        # ... existing code ...

        def process_vulnerability_entries(entries, tokenizer, model):
            """Process each vulnerability entry and calculate threat level"""
            results = []
            
            for entry in entries:
                # Combine entry information into a single text
                input_text = f"Test: {entry['Test']}\nDefinition: {entry['Definition']}\nRemediation: {entry['Remediation']}"
                
                # Generate threat score for this entry
                input_ids = tokenizer(input_text, return_tensors="pt").input_ids
                outputs = model.generate(input_ids)
                raw_output = tokenizer.decode(outputs[0])
                
                # Extract number from output
                number_match = re.search(r'(\d+\.?\d*)', raw_output)
                if number_match:
                    score = float(number_match.group(1))
                    
                    # Categorize individual threat level
                    if 0 <= score <= 4:
                        threat_level = f"Low-{score:.2f}"
                    elif 4.1 <= score <= 7:
                        threat_level = f"Medium-{score:.2f}"
                    elif 7.1 <= score <= 10:
                        threat_level = f"High-{score:.2f}"
                    else:
                        threat_level = "Invalid Score Range"
                        
                    results.append({
                        'name': entry['Test'],
                        'score': score,
                        'threat_level': threat_level
                    })
            
            return results
        
        from transformers import T5Tokenizer, T5ForConditionalGeneration

# # Define report folder path
        scenario_folder = "/Users/apple/Desktop/Web-Vulnerability-Scanner/Mitre-Att&ck/src/ScenarioBank"

        # Get the file from report folder (assuming there's only one file)
        file_path = os.path.join(scenario_folder, os.listdir(scenario_folder)[0])

#         # Read the content of the file
#         with open(file_path, 'r') as file:
#             input_text = file.read()

#         st.info("Calculating Threat Level...")
#         st.info("Loading Tokenizer...")
#         tokenizer = T5Tokenizer.from_pretrained("ethedeltae/flan-t5-small-sih")
#         st.info("Loading Model...")
#         model = T5ForConditionalGeneration.from_pretrained("ethedeltae/flan-t5-small-sih")

#         input_ids = tokenizer(input_text, return_tensors="pt").input_ids
#         st.info("Generating Output...")
#         outputs = model.generate(input_ids)

#         # Get the raw output and clean it using regex
#         import re
#         raw_output = tokenizer.decode(outputs[0])
#         number_match = re.search(r'(\d+\.?\d*)', raw_output)  # Matches whole numbers and decimals

#         if number_match:
#             number = float(number_match.group(1))
            
#             # Categorize the number
#             if 0 <= number <= 4:
#                 result = f"Low-{number}"
#             elif 4.1 <= number <= 7:
#                 result = f"Medium-{number}"
#             elif 7.1 <= number <= 10:
#                 result = f"High-{number}"
#             else:
#                 result = "Invalid Number Range"
                
#             st.write(result)
#         else:
#             st.write("No valid number found in output")
        st.info("Calculating Threat Level...")
        st.info("Loading Tokenizer...")
        tokenizer = T5Tokenizer.from_pretrained("ethedeltae/flan-t5-small-sih")
        st.info("Loading Model...")
        model = T5ForConditionalGeneration.from_pretrained("ethedeltae/flan-t5-small-sih")

        # Read and parse the vulnerability file
        with open(file_path, 'r') as file:
            input_text = file.read()

        # Parse entries
        vulnerability_entries = parse_vulnerability_entries(input_text)

        # Process entries and get individual threat scores
        threat_results = process_vulnerability_entries(vulnerability_entries, tokenizer, model)

        # Display results
        st.write("Vulnerability Threat Levels")
        for result in threat_results:
            st.write(f"""
                **Test**: {result['name']}  
                **Threat Level**: {result['threat_level']}
                ---
            """)
        
        if scan_results:
            st.title("Security Scan Results")
            
            # # Convert scan results to DataFrame
            df = pd.DataFrame(scan_results)
            # # Create styling for threat levels
            # threat_level_style = JsCode("""
            #     function(params) {
            #         if (params.value === 'High') {
            #             return {'backgroundColor': '#E1ABAB', 'font-style': 'italic', 'box-shadow': 'inset 0 0 20px 10px #F47A7A', 'text-align': 'center', 'border-radius': '10px'};
            #         } else if (params.value === 'Medium') {
            #             return {'backgroundColor': '#FCDDA9', 'font-style': 'italic', 'box-shadow': 'inset 0 0 20px 10px #E5C082', 'text-align': 'center', 'border-radius': '10px'};
            #         } else if (params.value === 'Low') {
            #             return {'backgroundColor': '#CDE1AB', 'font-style': 'italic', 'box-shadow': 'inset 0 0 20px 10px #A8E594', 'text-align': 'center', 'border-radius': '10px'};
            #         } else if (params.value === 'Safe') {
            #             return {'backgroundColor': '#FCEFA9', 'font-style': 'italic', 'box-shadow': 'inset 0 0 20px 10px #E7D574', 'text-align': 'center', 'border-radius': '10px'};
            #         }
            #     }
            # """)
            
            # status_style = JsCode("""
            #     function(params) {
            #         if (params.value === 'Completed') {
            #             return {'color': '#6AD652'};
            #         } else if (params.value === 'Skipped') {
            #             return {'color': '#E1ABAB'};
            #         }
            #     }
            # """)

            # bg_color = JsCode("""
            #     function(params) {
            #         if (params.value !== '') {
            #             return {'backgroundColor': 'rgba(225, 246, 255, 0.9)', 'border-radius': '10px'};
            #         }
            #     }
            # """)

            # # Define the formatter for the table
            # formatter = {
            #     'Test Name': ('Test Name', PINLEFT),
            #     'Status': (
            #         'Status', {
            #             'width': 120,
            #             'cellStyle': status_style
            #         }
            #     ),
            #     'Time Taken': ('Time Taken', {'width': 100}),
            #     'Threat Level': (
            #         'Threat Level',
            #         {
            #             'width': 50,
            #             'cellStyle': threat_level_style
            #         }
            #     )
            # }

            # # Apply the table with AgStyler
            # grid_response = draw_grid(
            #     df=df,
            #     formatter=formatter,
            #     fit_columns=True,
            #     use_checkbox=True,
            #     max_height=700,
            # )

            # # Display selected rows if any
            # if grid_response['selected_rows']:
            #     st.subheader("Selected Vulnerabilities")
            #     selected_df = pd.DataFrame(grid_response['selected_rows'])
            #     st.dataframe(
            #         selected_df,
            #         column_config={
            #             "Test Name": st.column_config.TextColumn("Test Name", width="medium"),
            #             "Status": st.column_config.TextColumn("Status", width="small"),
            #             "Time Taken": st.column_config.TextColumn("Time Taken", width="small"),
            #             "Threat Level": st.column_config.TextColumn("Threat Level", width="small"),
            #         },
            #         hide_index=True,
            #     )

            # Display summary statistics
            st.subheader("Threat Level Summary")
            col2, col3, col4, col5, col6 = st.columns(5)
            with col2:
                completed_tests = len(df[df['Status'] == 'Completed'])
                st.metric("Completed Tests", completed_tests)
            with col3:
                medium_threats = len(df[df['Threat Level'] == 'Critical'])
                st.metric("Critical Threats", medium_threats)
            with col4:
                high_threats = len(df[df['Threat Level'] == 'High'])
                st.metric("High Threats", high_threats)
            with col5:
                medium_threats = len(df[df['Threat Level'] == 'Medium'])
                st.metric("Medium Threats", medium_threats)
            with col6:
                low_threats = len(df[df['Threat Level'] == 'Low'])
                st.metric("Low Threats", low_threats)
            

            # st.success(f"Scan completed! Highest threat level detected: {highest_threat_level}")

        st.info("Running MITRE Att&ck...")
# Define the report folder path
        report_folder = "/Users/apple/Desktop/Web-Vulnerability-Scanner/Mitre-Att&ck/src/ScenarioBank"
        scenario_folder = "/Users/apple/Desktop/Web-Vulnerability-Scanner/Mitre-Att&ck/src/ScenarioBank"
        scan_results_folder = "/Users/apple/Desktop/Web-Vulnerability-Scanner/scan_results"
        # Process any file found in the folder
        for filename in os.listdir(scenario_folder):
            file_path = os.path.join(scenario_folder, filename)

        # Delete folder contents after processing
        processThreatsScenario(file_path)
        def delete_folder_contents(folder_path):
            try:
                shutil.rmtree(folder_path)
                os.makedirs(folder_path)
            except Exception as e:
                print(f"Error cleaning folder: {e}")

        # Clean up after processing
        report_file_1 = ""
        for file_name in os.listdir(report_folder):
            if re.search(r'Atk', file_name, re.IGNORECASE) and file_name.endswith(".json"):
                report_file_1 = os.path.join(report_folder, file_name)
                st.write(f"Found report file: {report_file_1}")
                break

        
        st.info("Completed MITRE Att&ck...")

        def generate_security_report(subdomains, ips, scan_output, ip_details, cvss_level, scan_results_df, mitre_report_path, output_path):
            timestamp = time.strftime("%Y%m%d-%H%M%S")
            report_path = f"{output_path}/security_report_{timestamp}.txt"
            
            with open(report_path, 'w') as report:
                # Write header
                report.write("==========================================\n")
                report.write("Security Assessment Report\n")
                report.write(f"Generated on: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
                report.write("==========================================\n\n")
                
                # Write DNS Enumeration Results
                report.write("1. DNS ENUMERATION RESULTS\n")
                report.write("------------------------------------------\n")
                report.write("1.1 Discovered Subdomains:\n")
                for subdomain in subdomains:
                    report.write(f"  - {subdomain}\n")
                
                report.write("\n1.2 Associated IP Addresses:\n")
                for ip in ips:
                    report.write(f"  - {ip}\n")
                    
                # Write IP Details
                report.write("\n2. IP Proxy ANALYSIS\n")
                report.write("------------------------------------------\n")
                for ip, details in ip_details.items():
                    report.write(f"IP: {ip}\n")
                    report.write(f"Details: {details}\n")
                    
                # Write Scan Output
                report.write("\n3. FUZZING RESULTS\n")
                report.write("------------------------------------------\n")
                # report.write(scan_output)

                for result in scan_output:
                    report.write(str(result))
                
                # Write CVSS Threat Level
                report.write("\n4. CVSS THREAT ASSESSMENT\n")
                report.write("------------------------------------------\n")
                # report.write(f"Threat Level: {cvss_level}\n")
                for result in threat_results:
                    report.write(f"""
                        **Test**: {result['name']}  
                        **Threat Level**: {result['threat_level']}
                        ---
                    """)
                
                
                # Write Scan Results DataFrame
                report.write("\n5. DETAILED VULNERABILITY ANALYSIS\n")
                report.write("------------------------------------------\n")
                report.write(scan_results_df.to_string())
                
                # Write MITRE ATT&CK Report
                report.write("\n6. MITRE ATT&CK FRAMEWORK ANALYSIS\n")
                report.write("------------------------------------------\n")
                try:
                    with open(mitre_report_path, 'r') as mitre_file:
                        mitre_data = json.load(mitre_file)
                        report.write(json.dumps(mitre_data, indent=2))
                except Exception as e:
                    report.write(f"Error reading MITRE report: {str(e)}\n")
            
            return report_path

            
        ip_details_dict = {}
        for ip in findings['ip_addresses']:
            ip_details_dict[ip] = get_ip_details(ip)

        report_path = generate_security_report(
            subdomains=findings['subdomains'],
            ips=findings['ip_addresses'],
            scan_output=fuzz_results,
            ip_details=ip_details_dict,
            cvss_level=result,
            scan_results_df=df,
            mitre_report_path=report_file_1,
            output_path="/Users/apple/Desktop/Web-Vulnerability-Scanner/full_report")

        with open(report_path, "r") as file:
           report_data_1 = file.read()
        st.download_button(
                label="Full Security Report",
                data=report_data_1,
                file_name="security_report.txt",
                mime="text/plain",
            )

        delete_folder_contents(scenario_folder)
        delete_folder_contents(scan_results_folder)
        st.success(f"Security report generated: {report_path}")

    except Exception as e:
        st.error(f"Failed to process URL: {str(e)}")
        st.info("Please ensure Chrome is installed and properly configured.")
elif submit_button:
    st.warning("Please enter a valid URL.")


    # Rename the index column if needed
    if 'enumeration_complete' not in st.session_state:
        st.session_state.enumeration_complete = False
    
    st.cache_data.clear()

    
    def check_404(url):
        try:
            response = requests.head(url)  # Use HEAD request for faster checking
            return response.status_code == 404
        except requests.RequestException:
            return False

    # Function to brute force valid URLs
    def brute_force_url(base_url):
        # This is a simple wordlist for the sake of demonstration.
            # In real scenarios, you might read from a .txt file.
            wordlist = ['about', 'contact', 'login', 'signup', 'user', 'admin']
            found_urls = []
            for word in wordlist:
                # Construct new URL to check
                new_url = base_url + "/" + word
                if not check_404(new_url):
                    found_urls.append(new_url)
            return found_urls
        


    if input_url != "":
        # Initialize a variable to store the final URL
        final_url = input_url
        # Check if the input URL ends with "404/" and remove it
        if input_url.endswith("404/"):
                final_url = input_url.rsplit("404/", 1)[0]
                statuscode += f"<br>{input_url} - Removed '404/': {final_url}"
        try:
            response = requests.get(final_url)  # Send a GET request to the URL
            if response.status_code == 200:
                statuscode += f'<div class = "checktest"><span style="font-weight:600;"> Status: 200 (OK)</span> - The website is live and running</span></div>'
                displaysvg = statusg_svg
            else:
                statuscode += f'<div class = "checktest"><span style="font-weight:600;"> Status:{response.status_code}</span> -  The website may have issues</div>'
                displaysvg = statusy_svg
                    

            if check_404(final_url):
                statuscode += f'<div class = "checktest"><span style="font-weight:600;"> Status:{response.status_code}</span> -  Status: 404 (Not Found) - Initiating Brute Force</div>'
                displaysvg = statusr_svg
                # Try to brute force the correct URL by modifying the final_url
                possible_urls = brute_force_url(final_url)
                if possible_urls:
                    final_url = possible_urls[0]  # Use the first valid URL found
                    statuscode += f"<br>Brute-forced URL: {final_url}"
                else:
                    statuscode += "<br>No valid URLs found based on the wordlist"
        except requests.RequestException as e:
                statuscode += f"<br>{final_url} NA FAILED TO CONNECT {str(e)}"
        except Exception as e:
                print(e)
                statuscode += "<br>Not sure what went wrong. We'll get back to you shortly."

        enumeration_complete = True

    if input_url:
        try:
            # Configure Chrome options
            chrome_options = Options()
            chrome_options.add_argument('--headless')
            chrome_options.add_argument('--no-sandbox')
            chrome_options.add_argument('--disable-dev-shm-usage')
            
            # Get screenshot
            driver = webdriver.Chrome(service=webdriver.chrome.service.Service(ChromeDriverManager().install()), 
                                    options=chrome_options)
            driver.get(input_url)
            screenshot = driver.get_screenshot_as_png()
            driver.quit()
            
            # Convert screenshot to PIL Image
            img = Image.open(BytesIO(screenshot))
            
            # Convert image to base64
            buffered = BytesIO()
            img.save(buffered, format="PNG")
            img_str = base64.b64encode(buffered.getvalue()).decode()
            
            # Process prediction
            try:
                phishing_url_detector = get_model()
                prediction = phishing_url_detector.predict(features_dataframe)
                if prediction == int(True):
                    predictmsg = f'<div style="display: flex; align-items: center; justify-content: center; gap: 12px;">{red_svg} <div style="font-size:20px; font-weight:600; color:#B01E1E;">Alert: Critical Warning: Critical Vulnerabilities Detected</div></div>'
                elif prediction == int(False):
                    predictmsg = f'<div style="display: flex; align-items: center; justify-content: center; gap: 12px;">{green_svg} <div style="font-size:20px; font-weight:600; color:#1EB035;">No suspicious activities identified.</div></div>'
                else:
                    predictmsg = ''
            except Exception as e:
                print(e)
                predictmsg = f'<div style="display: flex; align-items: center; justify-content: center; gap: 12px;">{yellow_svg} <div style="font-size:20px; font-weight:600; color:#FFD83C;">Error: Something went wrong. Please refresh the page!</div></div>'

            # Display results
            st.markdown(predictmsg, unsafe_allow_html=True)
            snapshot, table1 = st.columns([0.5, 0.5])
            with snapshot:

                st.markdown(f"""
                    <style>
                        .results-container {{
                        width: 100%;
                        display: flex;
                        justify-content: space-between;
                        gap: 20px;
                        margin: 0;
                        padding: 20px;
                    }}
                    
                    .screenshot-container {{
                        width: 50%;
                        background: rgba(255, 255, 255, 0.4);
                        border-radius: 15px;
                        padding: 20px;
                        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                    }}
                    
                    .status-code {{
                        margin:0;
                        padding: 3px;
                        border-radius: 8px;
                        background: transparent;
                        font-weight: 600;
                        font-size: 12px;
                    }}
                    
                    .screenshot-img {{
                        width: 100%;
                        height: auto;
                        border-radius: 8px;
                    }}
                    
                    .grid-container {{
                        width: 45%;
                        flex: 1;
                        background: rgba(255, 255, 255, 0.9);
                        border-radius: 15px;
                        padding: 20px;
                        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                    
                    }}
                    .ag-header-cell-label{{
                        font-weight: 600 !important;
                        background-color: red !important;

                    }}
                </style>
                
                <div class="results-container">
                    <div class="screenshot-container">
                        <div class="status-code">
                            {statuscode}
                        </div>
                        <div class="screenshot-img">
                            <img src="data:image/png;base64,{img_str}" style="width:100%; border-radius:8px;">
                        </div>
                    </div>
                </div>
            """, unsafe_allow_html=True)
            bg_color = JsCode("""
                    function(params) {
                        if (params.value !== '') {
                            return {'backgroundColor': 'rgba(225, 246, 255, 0.9)'};
                        }
                    }
                """)
            display_formatter = {
                'index': ('Parameter',
                            {'width': '50%',
                            'cellStyle': bg_color,
                            'textAlign': 'left'}),
                '0': ('Value',
                        {'width': '50%',
                        'cellStyle': bg_color,
                        'textAlign': 'left'}),
            }
            with table1:
                st.write("")
                display_grid_response = draw_grid(
                    df=display_dataframe,
                    formatter=display_formatter,
                    fit_columns=True,
                    use_checkbox=True,
                    max_height=300,
                )


            table_vulnerability()

                

        except Exception as e:
            st.error(f"Failed to process URL: {str(e)}")
            st.info("Note: Make sure the URL is accessible and includes 'http://' or 'https://'")

    

# if selected == "MITRE Chatbot":
# run_mitre(report)  --  att&ck and cwe report
# # run_mitre(report)  --  att&ck and cwe report
# print("Process Threat Completed...")
# st.empty()

#     report_data = {
#        "report_name": "MITRE 1 Report",
#        "data": [{"key": "value"}, {"key2": "value2"}]  # Ensure this is a list of dictionaries or simple data types
#    }
#if regex(for i in report_folder: i has "attk") then put to report_data_1
#if regex(for i in report_folder: i has "cwe")  then put to report_data_2
#report_data_1 = /report_folder/x.json
#report_data_2 = /report_folder/y.json

