"""
WebGuard: A Comprehensive Fuzzer for Web Application Security
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/13PhvS9RucBMO-DViNrLIu1aaYttGWiT0
"""

import streamlit as st
import pickle
import pandas as pd
from extract_features import ExtractFeatures
from PIL import Image
from io import BytesIO
import requests
import dns.resolver
from urllib.parse import urljoin
import streamlit.components.v1 as components
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import base64
from st_aggrid import AgGrid, GridUpdateMode, JsCode
from st_aggrid.grid_options_builder import GridOptionsBuilder
from streamlit_option_menu import option_menu
import json
import os
import time
import sys
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage
from streamlit.components.v1 import html
from agstyler import PINLEFT, draw_grid, JsCode

# sys.path.append(os.path.join(os.path.dirname(file), 'Mitre-Att&ck'))
# from threats2MitreRun import processThreatsScenario

st.set_page_config(page_title="WebGuard", layout="wide")
# Load images


# Streamlit UI for logos
col1, col3 = st.columns([5,1.4])

  # Function to encode image to base64
def get_base64_encoded_image(image_path):
        with open(image_path, "rb") as img_file:
            return base64.b64encode(img_file.read()).decode()

sihlogo_base64 = get_base64_encoded_image("sihlogo.jpg")
webguard_base64 = get_base64_encoded_image("webguard.png")

def get_svg_content(svg_name):
    try:
        with open(f"{svg_name}.svg", "r") as file:
            return file.read()
    except FileNotFoundError:
        return ""
    
with col3:
    redirect_url = "https://github.com/iamaastharawat/CustomRules-VidhyaDhaar.git"

    # Encode the image to base64
    extension_button_new_base64 = get_svg_content("button-new")

    # Create a button with an image background
    st.markdown(f"""
        <style>
        .button {{
            background-color: #3c3c3c;
            height: 45px;  /* Adjust height */
            border: none;
            border-radius: 10px;
            cursor: pointer;
            color: white;
            padding-left: 10px;
            padding-right: 10px;
            font-weight: semibold;
            display: inline-block;
        }}
        .button:hover {{
            background-color: #4c4c4c;
        }}
        </style>
        <a href="{redirect_url}" target="_blank">
            <button class="button">{extension_button_new_base64} Try our Early Code Tester</button>
        </a>
    """, unsafe_allow_html=True)
    

    
def table_vulnerability():
    try:
        # Sample scan data
        scan_data = [
            {
                "Test Name": "Golismero Nikto Scans",
                "Status": "Completed",
                "Time Taken": "3s",
                "Expected Time": "45s",
                "Threat Level": "Safe"
            },
            {
                "Test Name": "XSS Vulnerability Check",
                "Status": "Completed",
                "Time Taken": "2s",
                "Expected Time": "45s",
                "Threat Level": "High"
            },
            {
                "Test Name": "SQL Injection Test",
                "Status": "Completed",
                "Time Taken": "4s",
                "Expected Time": "35s",
                "Threat Level": "High"
            },
            {
                "Test Name": "Directory Traversal Check",
                "Status": "Completed",
                "Time Taken": "2s",
                "Expected Time": "30s",
                "Threat Level": "Low"
            },
            {
                "Test Name": "CSRF Vulnerability Test",
                "Status": "Skipped",
                "Time Taken": "0s",
                "Expected Time": "30s",
                "Threat Level": "N/A"
            }
        ]

        # Convert to DataFrame
        df = pd.DataFrame(scan_data)

        if not df.empty:

            st.markdown('''
                        <style>
                        [data-testid="stMetric"] > div {
                            color: #00abd7 !important;
                            padding-bottom:20px;
                        }
                        </style>
                        ''',unsafe_allow_html=True)

            # Create a single JsCode object for all threat level conditions
            threat_level_style = JsCode("""
                function(params) {
                    if (params.value === 'High') {
                        return {'backgroundColor': 'rgba(225, 246, 255, 0.9)', 'font-style': 'italic' , 'text-align' : 'center', 'color' : '#F47A7A'};
            } else if (params.value === 'Medium') {
                return {'backgroundColor': 'rgba(225, 246, 255, 0.9)', 'font-style': 'italic' , 'text-align' : 'center', 'color' : '#E7D574'};
            } else if (params.value === 'Low') {
                return {'backgroundColor': 'rgba(225, 246, 255, 0.9)', 'font-style': 'italic' , 'text-align' : 'center', 'color' : '#A8E594'};
            } else if (params.value === 'Safe') {
                return {'backgroundColor': 'rgba(225, 246, 255, 0.9)', 'font-style': 'italic' , 'text-align' : 'center', 'color' : '#CDE1AB'};
            } 
        }
    """)
            status_style = JsCode("""
                function(params) {
                    if (params.value === 'Completed') {
                        return {'color': '#6AD652', 'background-color': 'rgba(225, 246, 255, 0.9)'};
                    } else if (params.value === 'Skipped') {
                        return {'color': '#E1ABAB', 'background-color': 'rgba(225, 246, 255, 0.9)'};
                    }
                }
            """)

            test_style = JsCode("""
                function(params) {
                    return {'width': 200, 'font-weight': 'semibold', 'background-color': 'rgba(225, 246, 255, 0.9)'};
                }
            """)

            time_style = JsCode("""
                function(params) {
                    return {'width': 100, 'background-color': 'rgba(225, 246, 255, 0.9)'};
                }
            """)






            # Define the formatter for the table
            formatter = {
                'Test Name': ('Test Name',{'width': 200, 'cellStyle' : test_style}),
                'Status': (
                    'Status', {
                                'width': 120,
                                'cellStyle' : status_style
                    }),
                'Time Taken': ('Time Taken', {'width': 100, 'cellStyle' : time_style}),
                'Expected Time': ('Expected Time', {'width': 100, 'cellStyle' : time_style}),
                'Threat Level': (
                    'Threat Level',
                    {
                        'width': 100,
                        'cellStyle': threat_level_style
                    }
                )

            }
            st.write("")
            st.write("")

            col1, col2, col3, col4, col5= st.columns(5)
        
            with col1:
                st.metric("Total Tests", len(df))
            with col2:
                completed_tests = len(df[df['Status'] == 'Completed'])
                st.metric("Completed Tests", completed_tests)
            with col3:
                high_threats = len(df[df['Threat Level'] == 'High'])
                st.metric("High Threats", high_threats)
            with col4:
                medium_threats = len(df[df['Threat Level'] == 'Medium'])
                st.metric("Medium Threats", medium_threats)
            with col5:
                low_threats = len(df[df['Threat Level'] == 'Low'])
                st.metric("Low Threats", low_threats)

            # Apply the table with AgStyler
            grid_response = draw_grid( 
                df = df,
                formatter=formatter, 
                fit_columns=True,  
                max_height=700,
                use_checkbox=True, 
                
            )


            if grid_response['selected_rows']:
                st.subheader("Selected Vulnerabilities")
                selected_df = pd.DataFrame(grid_response['selected_rows'])
                st.dataframe(
                    selected_df,
                    column_config={
                        "Test Name": st.column_config.TextColumn("Test Name", width="medium"),
                        "Status": st.column_config.TextColumn("Status", width="small"),
                        "Time Taken": st.column_config.TextColumn("Time Taken", width="small"),
                        "Threat Level": st.column_config.TextColumn("Threat Level", width="small"),
                    },
                    hide_index=True,
        )

          
            
            st.subheader("Threat Distribution")
            threat_counts = df['Threat Level'].value_counts()
            st.bar_chart(threat_counts)

    except Exception as e:
        st.error(f"An error occurred: {str(e)}")
        st.info("Please make sure all required dependencies are installed.")


    
red_svg = get_svg_content("red")
green_svg = get_svg_content("green")
yellow_svg = get_svg_content("yellow")
statusg_svg = get_svg_content("statusg")
statusy_svg = get_svg_content("statusy")
statusr_svg = get_svg_content("statusr")





st.markdown("""
    <style>
      [data-testid="stAppViewContainer"] {
        overflow-x: hidden;
        max-width: 100vw;
    }
       ::-webkit-scrollbar {
        display: none;
    }

    /* Also prevent overflow on the main content */
    .main {
        overflow-x: hidden;
    }
     [data-testid="stSidebar"][aria-expanded="false"] {
        margin-left: -100px;
        width: 0px;
    }

    /* Sidebar default expanded state */
    [data-testid="stSidebar"][aria-expanded="true"] {
        margin-left: 0;
        width: 100px;
    }

    /* Ensure all transitions are smooth */
    [data-testid="stSidebar"] {
        transition: margin 0.3s, width 0.3s;
    }
    </style>
""", unsafe_allow_html=True)


   # Get the base64 encoded background image
try:
    bg_image = get_base64_encoded_image("bgchatbot.png")
    
    page_bg_color = f"""
    <style>
    [data-testid="stAppViewContainer"] {{
        background-image: url("data:image/png;base64,{bg_image}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        z-index: 100;
        margin-left: 0;
        margin:auto; !important
    }}
    [data-testid="stHeader"] {{
        background-image: url("data:image/png;base64,{bg_image}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        z-index: 100;
    }}

     [data-testid="stSidebar"] {{
            background-color: #343434;
            max-width: 100px;
            padding: 0;
            padding-right: -100px;
        }}
    [data-testid= "stCustomComponentV1"]{{
            background-color: #343434;
    }}


    </style>"""
    


    # Inject the CSS into the app
    st.markdown(page_bg_color, unsafe_allow_html=True)

except FileNotFoundError:
    st.error("Could not find bg.png - please check the file path")



st.markdown("""
            <style>
            .vsc-initialized{
                background-color:#343434;
                width: 100px !important;
                }
            
            [id="app"] > div > div > * {
                width: 100px !important;
            }

            [data-testid="stSidebarUserContent"] {
                margin-left: 50px !important;
                padding: 0 !important;
            }

            [data-testid="stMetric"] {
                color: #00abd7 !important ;
            }
            </style>

            """, unsafe_allow_html = True)
with col1:
    with st.sidebar:
        # Replace file-based image with base64 image
        st.markdown(f"""
            <img src="data:image/png;base64,{sihlogo_base64}" 
                 width="110px"
                 style="margin-left: 0px; margin-right:0px;margin-top : -20px; display: block;">
            """, unsafe_allow_html=True)

        selected = option_menu(
                menu_title = None,
                options = ["Vulnerability Check", "MITRE Chatbot", "About"],
                icons =["speedometer","chat-left-text", "journal-plus"],
                default_index = 0,
                # orientation = "horizontal",
                styles={
                "container": {"margin-bottom": "15px", "margin-left": "0", "background-color": "#343434", "border-radius": "0px", "border":"10px solid #343434"},
                "icon": {"color": "#00ABD7", "font-size": "22px", "align-items":"right",}, 
                "nav-link": {"font-size": "0px","color":"transparent", "align-items": "center", "margin-left":"0px", "--hover-color": "transparent", "background-color": "transparent", "width":"55px","padding-right":"0px","border-radius":"45px"},
                "nav-link-selected": {"border": "0px solid white","border-radius":"45px 0px 0px 45px", "background-color":"#E7F8FE", "transition":"width 1s ease-in-out, background-color 1s ease-in-out, border-radius 1s ease-in-out", "width": "200px", "transform-origin": "left"},
            }
        )

        
if selected == "Vulnerability Check":

    # with col2:
    #     st.markdown('<div class="image-container">', unsafe_allow_html=True)
    #     st.image(image, output_format="auto")
    #     st.markdown('</div>', unsafe_allow_html=True)

    # with col3:
    #     st.markdown('<div class="image-containers">', unsafe_allow_html=True)
    #     st.image(image2, output_format="auto")
    #     st.markdown('</div>', unsafe_allow_html=True)



    html_code = '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="sihlogo.ico">
    <title>WebGuard</title>
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
    @import url('https://fonts.cdnfonts.com/css/switzer');
        /* Reset some default styles */
        * {
        max-width: 100vw;
        box-sizing: border-box;
        margin: 0;
        padding: 0;
        }
        
        .stMain{
        max-width: 100vw;
        }

        body {
        font-family: 'Inter', sans-serif;
        background-color: #000;
        color: #000;
        }

        .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 2rem;
        }

        header {
        text-align: center;
        margin-bottom: 0;
        }


        h1{
            color: #000;
            font-family: 'Switzer', sans-serif;
            font-weight: 400;
            font-size: 2.5rem;
        

        }

        /* Existing CSS styles */
    
        
        /* Add these new styles for the URL input text area */
        [data-testid="stTextArea"] label {
            font-size: 18px !important;
            font-weight: bold !important;
            color: #A3B8EF !important;
        }
        
        [data-testid="stTextArea"] textarea::placeholder {
            color: black !important;
        }
        
        [data-testid="stTextArea"] textarea {
            color: #28B7DA !important;
            caret-color: #28B7DA !important;
            font-size: 16px !important;
            padding-left: 40px !important;
            padding-top: 3vh !important;
            max-height: 40px !important;
            width: 70vw !important;
            margin: auto !important;
            background-color: rgba(65, 175, 255, 0.17); !important;
            background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="%23000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg>') !important;
            background-repeat: no-repeat !important;
            background-position: 10px center !important;
            border: 8px solid #A3B8EF !important;
            border-color: #A3B8EF !important;
            border-radius: 90px !important;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1) !important;
            font-family: 'Inter', sans-serif;
        }
        
        [data-testid="stTextArea"] textarea:focus {
            border-color: #00ABD7 !important;
            outline: none !important;
            color: #000 !important;
        }

        .st-c0 {
            min-height: 70px;
            margin-bottom: 10px !important;
        }

        h2 {
            font-family: 'Inter', sans-serif;
            margin-top: -3vh;
        }

        .heading {
            margin-top: -20vh;
            width: 60vw;
            text-align: center;
            margin: auto;
        }


        .animated-text span{
            position: relative;
        }

        .animated-text span::before{
            content: "Your first step to a safer web";
            animation: words 15s infinite;
        }

        .animated-text span::after{
            content: "";
            position: absolute;
            width: calc(100% + 20px);
            height: 110%;
            background-color: #F5FFFE;
            border-left: 3px solid #00ABD7;
            right: -5px;
            animation: cursor 0.75s infinite, typing 15s steps(45) infinite;
        }

        @keyframes cursor {
            to{
                border-left: 2px solid #ff7f5000;
            }
        }

        @keyframes words {
            0%,20%{
                content:"Detect vulnerabilities in an instant";
                transition:0.5s ease-in-out;

            }
            27%,55%{
                content:"Brute force exceptions and authentication";
                transition:0.5s ease-in-out;
            }
            75%,90%{
                content: "Your first step to a safer web";
                transition:0.5s ease-in-out;
            }
        }

        @keyframes typing {
            10%,30%,50%,70%,90%{
                width: 0;
            }
            20%,25%,40%,60%,65%,80%,85%{
                width: calc(100% + 5px);
            }
        }
        .animated-text span{
            color: #000;
            font-family: 'Switzer', sans-serif;
            font-weight: 400;
            font-size: 2.2rem;
        
        }
        
    </style>
    </head>
    <body>
    <div class="heading" style="padding-top: 10vh;">
    <div class = "animated-text"><span></span></div>
    <h2 style="color: #3B5574; display: inline-block;font-style: italic; font-weight: 400; font-size: 1.75rem; padding-top: -3vh;">Test smarter, secure stronger.</h2>
    </div>
    </body>
    </html>'''

    st.markdown(html_code, unsafe_allow_html=True)

    # Function to encode image to base64
    def get_base64_encoded_image(image_path):
        with open(image_path, "rb") as img_file:
            return base64.b64encode(img_file.read()).decode()

    # Get the base64 encoded background image
    try:
        bg_image = get_base64_encoded_image("bg.png")
        
        page_bg_color = f"""
        <style>
        [data-testid="stAppViewContainer"] {{
            background-image: url("data:image/png;base64,{bg_image}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            z-index: 100;
        }}
        [data-testid="stHeader"] {{
        background-image: url("data:image/png;base64,{bg_image}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            z-index: 100;
        }}
        [data-testid="stSidebar"] {{
            background-color: #343434;
            width: 100px !important;
            padding: 0 !important;
        }}
        .stTextInput > div > div > input {{
            background-color : rgba(65, 175, 255, 0.17);
            border: 4px solid #A3B8EF !important;
            border-radius: 90px;
            color: black !important;
        }}

        /* Make sure list items are also black */
        li {{
            color: black !important;
        }}

        [data-testid="stTextArea"] {{
            display: flex;
        }}
        
        [data-testid="stTextArea"] > div {{
            background-color: transparent !important;
            width: 600px;
            margin: auto;
            border: none !important;
        }}
        
        [data-testid="stTextArea"] > div > div {{
            background-color: transparent !important;
            border: none !important;
        }}

        /* Style the text area */
        .stTextArea textarea {{
            background-color: rgba(65, 175, 255, 0.17);
            border: 4px solid #00ABD7 !important;
            border-radius: 15px;
            color: black !important;
        }}
        /* Ensure all regular text and markdown text is black */
        p, .markdown-text-container {{
            color: black;
        }}
        /* Remove black background from text area container */
        .stTextArea {{
            background-color: transparent !important;
        }}
        
        /* Remove any additional container styling */
        .element-container {{
            background-color: transparent !important;
        }}

        /* Remove default streamlit container backgrounds */
        [data-testid="stForm"] {{
            background-color: transparent !important;
        }}

        .checktest{{
            display: flex;
            gap: 10px;
            text-align:left;
            font-weight:400;
            font-size: 14px;
            margin:0;
            color: black;
        }}
        </style>
        """
    except FileNotFoundError:
        st.error("Could not find bg.png - please check the file path")

    # Inject the CSS into the app
    st.markdown(page_bg_color, unsafe_allow_html=True)



    # Caching the phishing URL detection model
    @st.cache_resource
    def get_model():
        with open('phishing_url_detector.pkl', 'rb') as pickle_model:
            phishing_url_detector = pickle.load(pickle_model)
        return phishing_url_detector

    # Directory enumeration and file brute-forcing
    COMMON_DIRECTORIES = ["admin", "login", "test", "backup"]
    COMMON_EXTENSIONS = [".php", ".html", ".asp", ".js"]
    COMMON_SUBDOMAINS = ["www", "api", "mail", "ftp"]

    # Function to check if a URL returns a 404 error
    def check_404(url):
        try:
            response = requests.head(url, timeout=10)  # Use HEAD request for faster checking
            return response.status_code == 404
        except requests.RequestException:
            return False

    # Function to brute force valid URLs (directories and files)
    def brute_force_url(base_url):
        found_urls = []
        for directory in COMMON_DIRECTORIES:
            for ext in COMMON_EXTENSIONS:
                full_url = urljoin(base_url, f"{directory}{ext}")
                if not check_404(full_url):
                    found_urls.append(full_url)
        return found_urls

    # Function to brute force Virtual Hosts (subdomains)
    def fuzz_virtual_hosts(domain):
        found_vhosts = []
        for subdomain in COMMON_SUBDOMAINS:
            vhost = f"{subdomain}.{domain}"
            try:
                response = requests.get(f"http://{vhost}", timeout=10)
                if response.status_code == 200:
                    found_vhosts.append(vhost)
            except requests.RequestException:
                continue
        return found_vhosts

    # API endpoint fuzzing
    API_ENDPOINTS = ["/api/v1/", "/api/v2/", "/api/user/", "/api/admin/"]
    def test_api_endpoints(base_url):
        found_endpoints = []
        for endpoint in API_ENDPOINTS:
            full_url = urljoin(base_url, endpoint)
            try:
                response = requests.get(full_url, timeout=10)
                if response.status_code == 200:
                    found_endpoints.append(full_url)
            except requests.RequestException:
                continue
        return found_endpoints

    # URL parameter fuzzing
    def fuzz_parameters(base_url):
        payloads = ["' OR 1=1 --", "<script>alert('XSS')</script>", "../etc/passwd"]
        found_vulnerabilities = []
        for payload in payloads:
            fuzzed_url = f"{base_url}?param={payload}"
            try:
                response = requests.get(fuzzed_url, timeout=10)
                if response.status_code == 200:
                    found_vulnerabilities.append(fuzzed_url)
            except requests.RequestException:
                continue
        return found_vulnerabilities


    svg_btn = get_base64_encoded_image("submit.svg")

    button_style = """
        <style>
        [data-testid="stFormSubmitButton"] > button {
            content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='9 18 15 12 9 6'%3E%3C/polyline%3E%3C/svg%3E");
            background-color: #9FADCC;
            color: white;
            padding: 16px 16px;
            font-size: 16px;
            border-radius: 45px;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        [data-testid="stFormSubmitButton"] > button:focus {
            background-color: #00ABD7;
        }

        [data-testid="stFormSubmitButton"]{
            position: relative;
            margin-left: 535px;
        
            bottom: 79px;
          
        }
         [data-testid="stForm"] {
            background-color: transparent !important;
            padding: 0 !important;
            margin: auto !important;
            display: flex;
            justify-content: center;
            border:none !important;
        }
        </style>
    """
    # Inject the custom CSS
    st.markdown(button_style, unsafe_allow_html=True)

    # Subdomain brute force discovery
    def discover_subdomains(domain):
        found_subdomains = []
        for subdomain in COMMON_SUBDOMAINS:
            try:
                resolved = dns.resolver.resolve(f"{subdomain}.{domain}", 'A')
                found_subdomains.append(f"{subdomain}.{domain}")
            except (dns.resolver.NXDOMAIN, dns.resolver.Timeout):
                continue
        return found_subdomains

    # Variables for the results
    statuscode = ""
    predictmsg = ""
    img = ""
    features_dataframe = ""
    grid_options = ""
    displaysvg = ""
    display_dataframe = ""
    with st.form(key='url_form', clear_on_submit=True):
        # Input for URL
        input_url = st.text_area("", placeholder="Enter the URL to test for vulnerabilities")
    
        # Submit button inside the form
        submit_button = st.form_submit_button("  ")

    if (input_url or submit_button) and not input_url.startswith(('http://', 'https://')):
        input_url = 'https://' + input_url
    if input_url != "":
        # Extracts features from the URL and converts it into a dataframe
        features_url = ExtractFeatures().url_to_features(url=input_url)
        features_dataframe = pd.DataFrame.from_dict([features_url])
        features_dataframe = features_dataframe.fillna(-1)
        features_dataframe = features_dataframe.astype(int)
        # Initialize the session state for enumeration_complete if it doesn't exist
        display_dataframe = features_dataframe.copy()
        display_dataframe = display_dataframe.transpose()

        
        display_dataframe.columns = display_dataframe.columns.map(str)
        # Reset index to include it in the display
        display_dataframe.reset_index(inplace=True)
        bg_color = JsCode("""
                function(params) {
                    if (params.value !== '') {
                        return {'backgroundColor': 'rgba(225, 246, 255, 0.9)'};
                    }
                }
            """)
        display_formatter = {
            'index': ('Parameter',
                          {'width': '50%',
                           'cellStyle': bg_color,
                           'textAlign': 'left'}),
            '0': ('Value',
                      {'width': '50%',
                       'cellStyle': bg_color,
                       'textAlign': 'left'}),
        }


        # Rename the index column if needed
        if 'enumeration_complete' not in st.session_state:
            st.session_state.enumeration_complete = False


        st.cache_data.clear()

        
        def check_404(url):
            try:
                response = requests.head(url)  # Use HEAD request for faster checking
                return response.status_code == 404
            except requests.RequestException:
                return False

        # Function to brute force valid URLs
        def brute_force_url(base_url):
            # This is a simple wordlist for the sake of demonstration.
                # In real scenarios, you might read from a .txt file.
                wordlist = ['about', 'contact', 'login', 'signup', 'user', 'admin']
                found_urls = []
                for word in wordlist:
                    # Construct new URL to check
                    new_url = base_url + "/" + word
                    if not check_404(new_url):
                        found_urls.append(new_url)
                return found_urls
            
       

        if input_url != "":
            # Initialize a variable to store the final URL
            final_url = input_url
            # Check if the input URL ends with "404/" and remove it
            if input_url.endswith("404/"):
                    final_url = input_url.rsplit("404/", 1)[0]
                    statuscode += f"<br>{input_url} - Removed '404/': {final_url}"
            try:
                response = requests.get(final_url)  # Send a GET request to the URL
                if response.status_code == 200:
                    statuscode += f'<div class = "checktest"><span style="font-weight:600;"> Status: 200 (OK)</span> - The website is live and running</span></div>'
                    displaysvg = statusg_svg
                else:
                    statuscode += f'<div class = "checktest"><span style="font-weight:600;"> Status:{response.status_code}</span> -  The website may have issues</div>'
                    displaysvg = statusy_svg
                        

                # if check_404(final_url):
                #     statuscode += f'<div class = "checktest"><span style="font-weight:600;"> Status:{response.status_code}</span> -  Status: 404 (Not Found) - Initiating Brute Force</div>'
                #     displaysvg = statusr_svg
                #     # Try to brute force the correct URL by modifying the final_url
                #     possible_urls = brute_force_url(final_url)
                #     if possible_urls:
                #         final_url = possible_urls[0]  # Use the first valid URL found
                #         statuscode += f"<br>Brute-forced URL: {final_url}"
                #     else:
                #         statuscode += "<br>No valid URLs found based on the wordlist"
            except requests.RequestException as e:
                    statuscode += f"<br>{final_url} NA FAILED TO CONNECT {str(e)}"
            except Exception as e:
                    print(e)
                    statuscode += "<br>Not sure what went wrong. We'll get back to you shortly."

            enumeration_complete = True

        if input_url:
            try:
                # Configure Chrome options
                chrome_options = Options()
                chrome_options.add_argument('--headless')
                chrome_options.add_argument('--no-sandbox')
                chrome_options.add_argument('--disable-dev-shm-usage')
                
                # Get screenshot
                driver = webdriver.Chrome(service=webdriver.chrome.service.Service(ChromeDriverManager().install()), 
                                        options=chrome_options)
                driver.get(input_url)
                screenshot = driver.get_screenshot_as_png()
                driver.quit()
                
                # Convert screenshot to PIL Image
                img = Image.open(BytesIO(screenshot))
                
                # Convert image to base64
                buffered = BytesIO()
                img.save(buffered, format="PNG")
                img_str = base64.b64encode(buffered.getvalue()).decode()
                
                # Process prediction
                try:
                    phishing_url_detector = get_model()
                    prediction = phishing_url_detector.predict(features_dataframe)
                    if prediction == int(True):
                        predictmsg = f'<div style="display: flex; align-items: center; justify-content: center; gap: 12px;">{red_svg} <div style="font-size:20px; font-weight:600; color:#B01E1E;">Alert: Critical Warning: Critical Vulnerabilities Detected</div></div>'
                    elif prediction == int(False):
                        predictmsg = f'<div style="display: flex; align-items: center; justify-content: center; gap: 12px;">{green_svg} <div style="font-size:20px; font-weight:600; color:#1EB035;">No suspicious activities identified.</div></div>'
                    else:
                        predictmsg = ''
                except Exception as e:
                    print(e)
                    predictmsg = f'<div style="display: flex; align-items: center; justify-content: center; gap: 12px;">{yellow_svg} <div style="font-size:20px; font-weight:600; color:#FFD83C;">Error: Something went wrong. Please refresh the page!</div></div>'

                # Display results
                st.markdown(predictmsg, unsafe_allow_html=True)
                snapshot, table1 = st.columns([0.5, 0.5])
                with snapshot:

                    st.markdown(f"""
                        <style>
                            .results-container {{
                            width: 100%;
                            display: flex;
                            justify-content: space-between;
                            gap: 20px;
                            margin: 0;
                            padding: 20px;
                        }}
                        
                        .screenshot-container {{
                            width: 100%;
                            background: rgba(255, 255, 255, 0.4);
                            border-radius: 15px;
                            padding: 20px;
                            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                        }}
                        
                        .status-code {{
                            margin:0;
                            padding: 3px;
                            border-radius: 8px;
                            background: transparent;
                            font-weight: 600;
                            font-size: 12px;
                        }}
                        
                        .screenshot-img {{
                            width: 100%;
                            height: auto;
                            border-radius: 8px;
                        }}
                        
                        .grid-container {{
                            width: 45%;
                            flex: 1;
                            background: rgba(255, 255, 255, 0.9);
                            border-radius: 15px;
                            padding: 20px;
                            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                        
                        }}
                        .ag-header-cell-label{{
                            font-weight: 600 !important;
                            background-color: red !important;

                        }}
                    </style>
                    
                    <div class="results-container">
                        <div class="screenshot-container">
                            <div class="status-code">
                                {statuscode}
                            </div>
                            <div class="screenshot-img">
                                <img src="data:image/png;base64,{img_str}" style="width:100%; border-radius:8px;">
                            </div>
                        </div>
                    </div>
                """, unsafe_allow_html=True)
                with table1:
                    st.write("")
                    display_grid_response = draw_grid(
                        df=display_dataframe,
                        formatter=display_formatter,
                        fit_columns=True,
                        use_checkbox=True,
                        max_height=350,
                        width=400,
                    )


                table_vulnerability()

                    

            except Exception as e:
                st.error(f"Failed to process URL: {str(e)}")
                st.info("Note: Make sure the URL is accessible and includes 'http://' or 'https://'")

        

if selected =="MITRE Chatbot":
    # run_mitre(report)  --  att&ck and cwe report
    # # run_mitre(report)  --  att&ck and cwe report
    # processThreatsScenario("vulnerability_new.txt")
    # print("Process Threat Completed...")
    # st.empty()
    
#     report_data = {
#        "report_name": "MITRE 1 Report",
#        "data": [{"key": "value"}, {"key2": "value2"}]  # Ensure this is a list of dictionaries or simple data types
#    }
   #if regex(for i in report_folder: i has "attk") then put to report_data_1
   #if regex(for i in report_folder: i has "cwe")  then put to report_data_2
   #report_data_1 = /report_folder/x.json
   #report_data_2 = /report_folder/y.json
    padl, mitre, padr = st.columns([0.05, 0.9, 0.05 ])

    # with mitreleft:
    remediation = "As the target is lacking this header, older browsers will be prone to Reflected XSS attacks. With this vulnerability the attacker will be able to perform a MiTM attack and thus compromising the confidentiality factor. The email address of the administrator and other information (address, phone, etc) is available publicly."
    #     report_options = st.selectbox("Select Report to Download", ["MITRE 1 Report", "MITRE 2 Report"])
    #     if report_options == "MITRE 1 Report":
    #         report_json = json.dumps(report_data)
    #         st.download_button("Download Report", report_json_1, "mitre_1_attk_report.json", "application/json")
    #         # delete from report_folder
    #     elif report_options == "MITRE 2 Report": # Replace with actual report data
    #         report_json = json.dumps(report_data)
    #         st.download_button("Download Report", report_json_2, "mitre_2_cwe_report.json", "application/json")
    #         # delete from report_folder

    chatbot_style = """
    <style>
        .chat-message {
            margin: 10px 0; /* Space between messages */
            padding: 10px; /* Padding for messages */
            border-radius: 10px; /* Rounded corners for messages */
        }
        .user-message {
            text-align: right; /* Align user messages to the right */
        }
        .assistant-message {
            text-align: left; /* Align assistant messages to the left */
        }
        .chat-input {
            margin-top: 20px; /* Space above input */
            display: flex; /* Flexbox for input and button */
        }

        .remediationstyle{
        font-family: 'Inter', sans-serif;
        text-align: left;
        font-size: 16px !important;
        color: #767676; 
        transition: opacity 3s ease-in-out;
        margin-top : 2vh;
        }
        
        
        .st-c0 {
            min-height: 70px;
            margin-bottom: 10px !important;
        }

        h2 {
            font-family: 'Inter', sans-serif;
            margin-top: -3vh;
        }

        /* Ensure all regular text and markdown text is black */
        p, .markdown-text-container {{
            color: black;
        }}
        /* Remove black background from text area container */
        .stTextArea {{
            margin-top :0px !important;
            background-color: transparent !important;
        }}
        
        /* Remove any additional container styling */
        .element-container {{
            background-color: transparent !important;
        }}

        /* Remove default streamlit container backgrounds */
        [data-testid="stForm"] {{
            background-color: transparent !important;
        }}
        

    </style>
    """
    
    svg_btn = get_base64_encoded_image("submit.svg")

    # Inject the custom CSS into the app
    st.markdown(chatbot_style, unsafe_allow_html=True)

    # Update the chatbot area layout
    with mitre:
        try:
            user_avatar_base64 = get_base64_encoded_image("user_avatar.png")
            assistant_avatar_base64 = get_base64_encoded_image("assistant_avatar.png")
    
            # If either avatar fails to load, use default values
            if not user_avatar_base64 or not assistant_avatar_base64:
                # Provide default avatar base64 strings
                user_avatar_base64 = "default_user_avatar_base64_string"
                assistant_avatar_base64 = "default_assistant_avatar_base64_string"
                st.warning("Using default avatars as image files couldn't be loaded")
        except Exception as e:
            st.error(f"Error loading avatars: {str(e)}")
            # Provide default avatar base64 strings
            user_avatar_base64 = "default_user_avatar_base64_string"
            assistant_avatar_base64 = "default_assistant_avatar_base64_string"
        st.markdown("""
                <style>
                .blue-btn{
                    color : #4B4B4B;
                    background-color : #63D3F1;
                    padding : 8px;
                    border-radius:12px;
                    width: 19vw;
                    font-weight : 600;
                    font-size: 20px;
                    align-items:center;
                    text-align:center;
                    margin-top : -8vh;
                }
                .gradient-text{
                            font-family: 'Inter', sans-serif;
                            letter-spacing: -0.1rem;
                            font-size:3rem;
                            font-weight: 600;
                            background: linear-gradient(to right, #000, #00ABD7);
                            -webkit-background-clip: text;
                            -webkit-text-fill-color: transparent;
                        }
                .chat-container{
                        max-height: 80vh;
                        overflow-y: auto;
                        display: flex;
                        flex-direction: column;
                        }
                    
                h1{
                        font-family: 'Inter', sans-serif;
                        letter-spacing: -0.1rem;
                        font-size:3rem;
                        font-weight: 600;
                        color:black;
                        text-align :center;
                    }
                """, unsafe_allow_html = True)
        avatar_style = f"""
            <style>
        .user-message {{
            position: relative;
            margin-right: 100px;  /* Make space for avatar */
        }}
        
        .assistant-message {{
            position: relative;
            padding-left: 100px;  /* Make space for avatar */
        }}

        .user-message::after {{
            content: '';
            position: absolute;
            right: -50px;  /* Moved inside the message container */
            top: 50%;
            transform: translateY(-50%);
            width: 35px;
            height: 35px;
            background-image: url("data:image/png;base64,{user_avatar_base64}");
            background-size: cover;
            background-position: center;
            border-radius: 50%;
        }}

        .assistant-message::before {{
            content: '';
            position: absolute;
            left: -50px;  /* Moved inside the message container */
            top: 50%;
            transform: translateY(-50%);
            width: 35px;
            height: 35px;
            background-image: url("data:image/png;base64,{assistant_avatar_base64}");
            background-size: cover;
            background-position: center;
            border-radius: 50%;
            z-index: 100;
            }}
        .bluebar{{
            margin: 3vh auto;
            height: 4px;
            background-color: rgba(147, 196, 244, 0.3);
            width: 1000px;
            border-radius: 16px;
        }}

        </style>
"""
        st.markdown(avatar_style, unsafe_allow_html=True)
    

        st.markdown(f"""
            <div class ="blue-btn">Vulnerabililty Remediations</div>
            <div class = "remediationstyle" >{remediation}</div>

            <div style = "padding-top : 30px; color : #000; font-weight:medium; ">Select Report to Download</div>
                
        """, unsafe_allow_html=True)
        report_data_1 = {"key": "value1", "key2": "value2"}
        report_data_2 = {"key": "value3", "key4": "value4"}

        # Convert reports to JSON format
        report_json_1 = json.dumps(report_data_1, indent=4)
        report_json_2 = json.dumps(report_data_2, indent=4)

        # Layout for displaying both download buttons side by side
        col1, col2, colpad = st.columns([1.2,1.2,3.6])

        with col1:
            st.download_button(
                label="MITRE ATT&CK Report",
                data=report_json_1,
                file_name="mitre_1_attk_report.json",
                mime="application/json",
            )

        with col2:
            st.download_button(
                label="MITRE CWE Report",
                data=report_json_2,
                file_name="mitre_2_cwe_report.json",
                mime="application/json",
            )

        st.markdown(f"""
            <div class = "bluebar" ></div>
                
        """, unsafe_allow_html=True)
        # Set the default model in session state
        if "groq_model" not in st.session_state:
            st.session_state["groq_model"] = "qwen3:4b"

        # Initialize chat history
        if "messages" not in st.session_state:
                st.session_state.messages = [
                {"role": "assistant", "content": f"Here's what I found about the vulnerabilities: {remediation}\n\nHow can I help you understand this better?"}
            ]

        # CSS for the chat UI
        st.markdown("""
            <style>
            .chat-container {
                max-width: 90vw;
                margin: 0 auto;
                background-color: transparent;
            }
            .gradient-text {
                background: linear-gradient(to right, #000, #00ABD7);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
            }
            .chat-messages {
                height: 50vh;
                overflow-y: auto;
                border: 0px solid #ddd;
                border-radius: 8px;
                padding: 10px;
                background: transparent;
            }
            .chat-message {
                display: inline-block;
                max-width: 70%;
                margin: 10px 100px; /* Add horizontal margin to prevent overflow */
                padding: 10px 100px; /* Increase padding to make room for avatars */
                border-radius: 8px;
                border: 1px solid #ddd;
                word-wrap: break-word;
                clear: both;
                width: auto;
                background-color: white;
                position: relative;  /* For avatar positioning */
            }
            .user-message {
                float: right;
                right:50px;
                border-right: 5px solid black;
                margin-right: 100px;  /* Space for avatar */
            }
            .assistant-message {
                float: left;
                left:50px;
                border-left: 5px solid black;
                margin-left: 100px;  /* Space for avatar */
            }
            .avatar {
                width: 35px;
                height: 35px;
                border-radius: 50%;
                bottom: 10px;
            }
            
            </style>
        """, unsafe_allow_html=True)

        # Display the chat header and description
        st.markdown("""
            <div class="chat-container">
                <h1>How can we <span class="gradient-text">assist</span> you on this?</h1>
                <div style="text-align:center; width: 50vw; margin: auto; padding-bottom: 10px;" class = "remediationstyle">Navigate the complexities of vulnerability remediation with ease. We are here to provide precise solutions, tailored recommendations. Ask your questions and take a step closer to a safer digital environment.</div>
            </div>
        """, unsafe_allow_html=True)

        # Generate chat messages dynamically with avatars
        chat_messages_html = ""
        for message in st.session_state.messages:
            if message["role"] == "user":
                chat_messages_html += f'<div class="chat-message user-message">{message["content"]}</div>'
            else:
                chat_messages_html += f'<div class="chat-message assistant-message">{message["content"]}</div>'

        # Display the chat container with message
        st.markdown(f"""
            <div class="chat-container">
                <div class="chat-messages">
                    {chat_messages_html}
                </div>
            </div>
            """, unsafe_allow_html=True)

            # Create placeholder for latest messages
            # placeholder = st.empty()
            
            # If there are messages, update the placeholder with the latest one
            # if st.session_state.messages:
            #     last_message = st.session_state.messages[-1]
                
        # Add custom CSS for the chat input and button
        chat_input_style = """
        <style>
            /* Style for the form container */
            .stTextInput > div > div > input {
                background-color: transparent !important;
                border-radius: 45px;
                color: black !important;
            }

            /* Ensure ALL markdown text is black */
            .css-10trblm, .css-183lzff, .element-container div {
                color: black;
            }

            /* Make sure list items are also black */
            li {
                color: black !important;
            }
            
            [data-testid="stTextArea"] > div {
                background-color: rgba(140, 140, 140, 0.24) !important;
                width: 900px;
                min-height: 50px !important;
                max-height: 65px !important;
                margin: auto;
                border-radius: 45px;
                border: none !important;
            }
            [data-testid="InputInstructions"] {
                display : none !important;
                background-color: transparent !important;
            }

            [data-testid="stTextArea"] > div > div {
                background-color: transparent !important;
                border: none !important;
                padding: 8px 12px !important;
            }
             .st-c0 {
            min-height: 70px;
                margin-bottom: 10px !important;
            }

            /* Style the text area */
            .stTextArea textarea {
                background-color: transparent !important;
                border-radius: 45px;
                color: black !important;
                min-height: 40px !important;  // Set minimum height for textarea
    padding: 8px 12px !important;  // Add padding
                margin-top: 5px !important;   // Add some top margin
                resize: none !important;
            }

            /* Ensure all regular text and markdown text is black */
            p, .markdown-text-container {
                color: black;
            }

            /* Remove black background from text area container */
            .stTextArea {
                background-color: transparent !important;
            }
            
            /* Remove any additional container styling */
            .element-container {
                background-color: transparent !important;
            }

            /* Remove default streamlit container backgrounds */
            [data-testid="stForm"] {
                background-color: transparent !important;
            }
        </style>"""

        # Inject the custom CSS
        st.markdown(chat_input_style, unsafe_allow_html=True)

        button_style = """
            <style>
            [data-testid="stFormSubmitButton"] > button {
                content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='9 18 15 12 9 6'%3E%3C/polyline%3E%3C/svg%3E");
                background-color: #000;
                color: white;
                padding: 16px 16px;
                font-size: 16px;
                border-radius: 45px;
                border: none;
                cursor: pointer;
                transition: background-color 0.3s ease;
            }
            [data-testid="stFormSubmitButton"] > button:focus {
                background-color: #00ABD7;
            }

            [data-testid="stFormSubmitButton"]{
                position: relative;
                margin-left: 839px;
            
                bottom: 76px;
            
            }
            [data-testid="stForm"] {
                background-color: transparent !important;
                padding: 0 !important;
                margin: auto !important;
                display: flex;
                justify-content: center;
                border:none !important;
                margin-bottom: 10px !important;
            }
            [data-testid="stMain"] {
                margin-bottom: -220px !important;
            }

            </style>
        """


        # Inject the custom CSS
        st.markdown(button_style, unsafe_allow_html=True)

        # Create the chat form
        with st.form(key='chat_form', clear_on_submit=True):
            # Input for user prompt
            prompt = st.text_area("", placeholder="Type your query here...")
            
            # Submit button inside the form
            submit_button = st.form_submit_button("Send")

        # Send button to trigger the assistant response
        if submit_button and prompt:
            # Add the user message to the session state
            st.session_state.messages.append({"role": "user", "content": prompt})

            try:
                chat_model = ChatOllama(model=st.session_state["groq_model"], temperature=0.3)
                content = chat_model.invoke([HumanMessage(content=prompt)]).content
                if content:
                    st.session_state.messages.append({"role": "assistant", "content": content})
                # Add the assistant's response to the session state
                st.rerun()
            except Exception as e:
                st.error(f"Error: {str(e)}")