"""
WebGuard: A Comprehensive Fuzzer for Web Application Security
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/13PhvS9RucBMO-DViNrLIu1aaYttGWiT0
"""

import streamlit as st
import pickle
import pandas as pd
from extract_features import ExtractFeatures
from PIL import Image
from io import BytesIO
import requests
import dns.resolver
from urllib.parse import urljoin
import streamlit.components.v1 as components
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import base64
from st_aggrid import AgGrid, GridUpdateMode, JsCode
from st_aggrid.grid_options_builder import GridOptionsBuilder
from streamlit_option_menu import option_menu
import json
import os
from groq import Groq
import time
import sys
import os
import re
import shutil
import subprocess

from streamlit.components.v1 import html

sys.path.append(os.path.join(os.path.dirname(__file__), 'Mitre-Att&ck/src'))
sys.path.append(os.path.join(os.path.dirname(__file__), 'rapid_scan'))
from rapid_scan.streamlit_json_cli import perform_vulnerability_scan
from threats2MitreRun import processThreatsScenario

def setup_chrome_driver():
    chrome_options = Options()
    chrome_options.add_argument("--headless")  # Run in headless mode
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    
    try:
        service = Service(ChromeDriverManager().install())
        driver = webdriver.Chrome(service=service, options=chrome_options)
        return driver
    except Exception as e:
        st.error(f"Chrome setup failed: {str(e)}")
        st.info("Please install Chrome browser or check your installation.")
        return None

st.set_page_config(page_title="WebGuard", layout="wide")
# Load images
image2 = Image.open('webguard.png')
image = Image.open('sihlogo.jpg') 
# Streamlit UI for logos
col1, col4, col2, col3 = st.columns([5, 4, 1, 1])

  # Function to encode image to base64
def get_base64_encoded_image(image_path):
        with open(image_path, "rb") as img_file:
            return base64.b64encode(img_file.read()).decode()

sihlogo_base64 = get_base64_encoded_image("sihlogo.jpg")
webguard_base64 = get_base64_encoded_image("webguard.png")


# st.markdown("""
#     <script>
#         window.addEventListener('message', function(e) {
#             if (e.data.type === 'streamlit:message') {
#                 window.parent.Streamlit.setComponentValue(e.data.data);
#             }
#         });
#     </script>
# """, unsafe_allow_html=True)
# st.markdown(
#     """
#     <style>
#     .image-container {
#         margin-top: -25vh; /* Adjust this value to move the images up or down */
#         padding = -10vh;
#     }
#     .image-containers {
#         margin-top: -40vh; /* Adjust this value to move the images up or down */
#         padding = -10vh;
#     }
#     </style>
#     """,
#     unsafe_allow_html=True
# )
st.markdown("""
    <style>
      [data-testid="stAppViewContainer"] {
        overflow-x: hidden;
        max-width: 100vw;
    }
       ::-webkit-scrollbar {
        display: none;
    }

    /* Also prevent overflow on the main content */
    .main {
        overflow-x: hidden;
    }
     [data-testid="stSidebar"][aria-expanded="false"] {
        margin-left: -100px;
        width: 0px;
    }

    /* Sidebar default expanded state */
    [data-testid="stSidebar"][aria-expanded="true"] {
        margin-left: 0;
        width: 100px;
    }

    /* Ensure all transitions are smooth */
    [data-testid="stSidebar"] {
        transition: margin 0.3s, width 0.3s;
    }
    </style>
""", unsafe_allow_html=True)


   # Get the base64 encoded background image
try:
    bg_image = get_base64_encoded_image("bgchatbot.png")
    
    page_bg_color = f"""
    <style>
    [data-testid="stAppViewContainer"] {{
        background-image: url("data:image/png;base64,{bg_image}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        z-index: 100;
        margin-left: 0;
        margin:auto; !important
    }}
    [data-testid="stHeader"] {{
        background-image: url("data:image/png;base64,{bg_image}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        z-index: 100;
    }}

     [data-testid="stSidebar"] {{
            background-color: #343434;
            max-width: 100px;
            padding: 0;
            padding-right: -100px;
        }}
    [data-testid= "stCustomComponentV1"]{{
            background-color: #343434;
    }}


    </style>"""
    


    # Inject the CSS into the app
    st.markdown(page_bg_color, unsafe_allow_html=True)

except FileNotFoundError:
    st.error("Could not find bg.png - please check the file path")



st.markdown("""
            <style>
            .vsc-initialized{
                background-color:#343434;
                width: 100px !important;
                }
            
            [id="app"] > div > div > * {
                width: 100px !important;
            }

            [data-testid="stSidebarUserContent"] {
                margin-left: 50px !important;
                padding: 0 !important;
            }
            </style>

            """, unsafe_allow_html = True)
with col1:
    with st.sidebar:
        # Replace file-based image with base64 image
        st.markdown(f"""
            <img src="data:image/png;base64,{sihlogo_base64}" 
                 width="110px"
                 style="margin-left: 0px; margin-right:0px;margin-top : -20px; display: block;">
            """, unsafe_allow_html=True)

        selected = option_menu(
                menu_title = None,
                options = ["Vulnerability Check", "MITRE Chatbot", "About"],
                icons =["speedometer","chat-left-text", "journal-plus"],
                default_index = 0,
                # orientation = "horizontal",
                styles={
                "container": {"margin-bottom": "15px", "margin-left": "0", "background-color": "#343434", "border-radius": "0px", "border":"10px solid #343434"},
                "icon": {"color": "#00ABD7", "font-size": "22px", "align-items":"right",}, 
                "nav-link": {"font-size": "0px","color":"transparent", "align-items": "center", "margin-left":"0px", "--hover-color": "transparent", "background-color": "transparent", "width":"55px","padding-right":"0px","border-radius":"45px"},
                "nav-link-selected": {"border": "0px solid white","border-radius":"45px 0px 0px 45px", "background-color":"#E7F8FE", "transition":"width 1s ease-in-out, background-color 1s ease-in-out, border-radius 1s ease-in-out", "width": "200px", "transform-origin": "left"},
            }
        )

        
if selected == "Vulnerability Check": #button for rapid_scan

    # with col2:
    #     st.markdown('<div class="image-container">', unsafe_allow_html=True)
    #     st.image(image, output_format="auto")
    #     st.markdown('</div>', unsafe_allow_html=True)

    # with col3:
    #     st.markdown('<div class="image-containers">', unsafe_allow_html=True)
    #     st.image(image2, output_format="auto")
    #     st.markdown('</div>', unsafe_allow_html=True)


    def run_vulnerability_scanner():
    # Ensure the script is in the same directory
        subprocess.run([sys.executable, "vulnerability_scanner.py"])

    html_code = '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="sihlogo.ico">
    <title>WebGuard</title>
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
    @import url('https://fonts.cdnfonts.com/css/switzer');
        /* Reset some default styles */
        * {
        max-width: 100vw;
        box-sizing: border-box;
        margin: 0;
        padding: 0;
        }
        
        .stMain{
        max-width: 100vw;
        }

        body {
        font-family: 'Inter', sans-serif;
        background-color: #000;
        color: #000;
        }

        .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 2rem;
        }

        header {
        text-align: center;
        margin-bottom: 0;
        }


        h1{
            color: #000;
            font-family: 'Switzer', sans-serif;
            font-weight: 400;
            font-size: 2.5rem;
        

        }

        /* Existing CSS styles */
    
        
        /* Add these new styles for the URL input text area */
        [data-testid="stTextArea"] label {
            font-size: 18px !important;
            font-weight: bold !important;
            color: #A3B8EF !important;
        }
        
        [data-testid="stTextArea"] textarea::placeholder {
            color: black !important;
        }
        
        [data-testid="stTextArea"] textarea {
            color: #28B7DA !important;
            caret-color: #28B7DA !important;
            font-size: 16px !important;
            padding-left: 40px !important;
            padding-top: 3vh !important;
            max-height: 40px !important;
            width: 70vw !important;
            margin: auto !important;
            background-color: rgba(65, 175, 255, 0.17); !important;
            background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="%23000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg>') !important;
            background-repeat: no-repeat !important;
            background-position: 10px center !important;
            border: 8px solid #A3B8EF !important;
            border-color: #A3B8EF !important;
            border-radius: 90px !important;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1) !important;
            font-family: 'Inter', sans-serif;
        }
        
        [data-testid="stTextArea"] textarea:focus {
            border-color: #00ABD7 !important;
            outline: none !important;
            color: #000 !important;
        }

        .st-c0 {
            min-height: 70px;
            margin-bottom: 10px !important;
        }

        h2 {
            font-family: 'Inter', sans-serif;
            margin-top: -3vh;
        }

        .heading {
            margin-top: -20vh;
            width: 60vw;
            text-align: center;
            margin: auto;
        }


        .animated-text span{
            position: relative;
        }

        .animated-text span::before{
            content: "Your first step to a safer web";
            animation: words 15s infinite;
        }

        .animated-text span::after{
            content: "";
            position: absolute;
            width: calc(100% + 20px);
            height: 110%;
            background-color: #F5FFFE;
            border-left: 3px solid #00ABD7;
            right: -5px;
            animation: cursor 0.75s infinite, typing 15s steps(45) infinite;
        }

        @keyframes cursor {
            to{
                border-left: 2px solid #ff7f5000;
            }
        }

        @keyframes words {
            0%,20%{
                content:"Detect vulnerabilities in an instant";
                transition:0.5s ease-in-out;

            }
            27%,55%{
                content:"Brute force exceptions and authentication";
                transition:0.5s ease-in-out;
            }
            75%,90%{
                content: "Your first step to a safer web";
                transition:0.5s ease-in-out;
            }
        }

        @keyframes typing {
            10%,30%,50%,70%,90%{
                width: 0;
            }
            20%,25%,40%,60%,65%,80%,85%{
                width: calc(100% + 5px);
            }
        }
        .animated-text span{
            color: #000;
            font-family: 'Switzer', sans-serif;
            font-weight: 400;
            font-size: 2.2rem;
        
        }
        
    </style>
    </head>
    <body>
    <div class="heading" style="padding-top: 10vh;">
    <div class = "animated-text"><span></span></div>
    <h2 style="color: #3B5574; display: inline-block;font-style: italic; font-weight: 400; font-size: 1.75rem; padding-top: -3vh;">Test smarter, secure stronger.</h2>
    </div>
    </body>
    </html>'''

    st.markdown(html_code, unsafe_allow_html=True)

    # Function to encode image to base64
    def get_base64_encoded_image(image_path):
        with open(image_path, "rb") as img_file:
            return base64.b64encode(img_file.read()).decode()

    # Get the base64 encoded background image
    try:
        bg_image = get_base64_encoded_image("bg.png")
        
        page_bg_color = f"""
        <style>
        [data-testid="stAppViewContainer"] {{
            background-image: url("data:image/png;base64,{bg_image}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            z-index: 100;
        }}
        [data-testid="stHeader"] {{
        background-image: url("data:image/png;base64,{bg_image}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            z-index: 100;
        }}
        [data-testid="stSidebar"] {{
            background-color: #343434;
            width: 100px !important;
            padding: 0 !important;
        }}
        .stTextInput > div > div > input {{
            background-color : rgba(65, 175, 255, 0.17);
            border: 4px solid #A3B8EF !important;
            border-radius: 90px;
            color: black !important;
        }}

        /* Ensure ALL markdown text is black */
        .css-10trblm, .css-183lzff, .element-container div {{
            color: black;
        }}
        /* Make sure list items are also black */
        li {{
            color: black !important;
        }}

        [data-testid="stTextArea"] {{
            display: flex;
        }}
        
        [data-testid="stTextArea"] > div {{
            background-color: transparent !important;
            width: 600px;
            margin: auto;
            border: none !important;
        }}
        
        [data-testid="stTextArea"] > div > div {{
            background-color: transparent !important;
            border: none !important;
        }}

        /* Style the text area */
        .stTextArea textarea {{
            background-color: rgba(65, 175, 255, 0.17);
            border: 4px solid #00ABD7 !important;
            border-radius: 15px;
            color: black !important;
        }}
        /* Ensure all regular text and markdown text is black */
        p, .markdown-text-container {{
            color: black;
        }}
        /* Remove black background from text area container */
        .stTextArea {{
            background-color: transparent !important;
        }}
        
        /* Remove any additional container styling */
        .element-container {{
            background-color: transparent !important;
        }}

        /* Remove default streamlit container backgrounds */
        [data-testid="stForm"] {{
            background-color: transparent !important;
        }}

        .checktest{{ 
            text-align:center;
            font-weight:600;
            font-size: 24px;
            margin-top:15vh;
            margin-bottom:20vh;
        }}
        </style>
        """
    except FileNotFoundError:
        st.error("Could not find bg.png - please check the file path")

    # Inject the CSS into the app
    st.markdown(page_bg_color, unsafe_allow_html=True)



    # Caching the phishing URL detection model
    @st.cache_resource
    def get_model():
        with open('/Users/apple/Desktop/Web-Vulnerability-Scanner/phishing_url_detector.pkl', 'rb') as pickle_model:
            phishing_url_detector = pickle.load(pickle_model)
        return phishing_url_detector

    # Directory enumeration and file brute-forcing
    COMMON_DIRECTORIES = ["admin", "login", "test", "backup"]
    COMMON_EXTENSIONS = [".php", ".html", ".asp", ".js"]
    COMMON_SUBDOMAINS = ["www", "api", "mail", "ftp"]

    # Function to check if a URL returns a 404 error
    def check_404(url):
        try:
            response = requests.head(url, timeout=10)  # Use HEAD request for faster checking
            return response.status_code == 404
        except requests.RequestException:
            return False

    # Function to brute force valid URLs (directories and files)
    def brute_force_url(base_url):
        found_urls = []
        for directory in COMMON_DIRECTORIES:
            for ext in COMMON_EXTENSIONS:
                full_url = urljoin(base_url, f"{directory}{ext}")
                if not check_404(full_url):
                    found_urls.append(full_url)
        return found_urls

    # Function to brute force Virtual Hosts (subdomains)
    def fuzz_virtual_hosts(domain):
        found_vhosts = []
        for subdomain in COMMON_SUBDOMAINS:
            vhost = f"{subdomain}.{domain}"
            try:
                response = requests.get(f"http://{vhost}", timeout=10)
                if response.status_code == 200:
                    found_vhosts.append(vhost)
            except requests.RequestException:
                continue
        return found_vhosts

    # API endpoint fuzzing
    API_ENDPOINTS = ["/api/v1/", "/api/v2/", "/api/user/", "/api/admin/"]
    def test_api_endpoints(base_url):
        found_endpoints = []
        for endpoint in API_ENDPOINTS:
            full_url = urljoin(base_url, endpoint)
            try:
                response = requests.get(full_url, timeout=10)
                if response.status_code == 200:
                    found_endpoints.append(full_url)
            except requests.RequestException:
                continue
        return found_endpoints

    # URL parameter fuzzing
    def fuzz_parameters(base_url):
        payloads = ["' OR 1=1 --", "<script>alert('XSS')</script>", "../etc/passwd"]
        found_vulnerabilities = []
        for payload in payloads:
            fuzzed_url = f"{base_url}?param={payload}"
            try:
                response = requests.get(fuzzed_url, timeout=10)
                if response.status_code == 200:
                    found_vulnerabilities.append(fuzzed_url)
            except requests.RequestException:
                continue
        return found_vulnerabilities


    svg_btn = get_base64_encoded_image("submit.svg")

    button_style = """
        <style>
        [data-testid="stFormSubmitButton"] > button {
            content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='9 18 15 12 9 6'%3E%3C/polyline%3E%3C/svg%3E");
            background-color: #9FADCC;
            color: white;
            padding: 16px 16px;
            font-size: 16px;
            border-radius: 45px;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        [data-testid="stFormSubmitButton"] > button:focus {
            background-color: #00ABD7;
        }

        [data-testid="stFormSubmitButton"]{
            position: relative;
            margin-left: 535px;
        
            bottom: 79px;
          
        }
         [data-testid="stForm"] {
            background-color: transparent !important;
            padding: 0 !important;
            margin: auto !important;
            display: flex;
            justify-content: center;
            border:none !important;
        }
        </style>
    """


    # Inject the custom CSS
    st.markdown(button_style, unsafe_allow_html=True)
        # button_style = """
    #     <style>
    #     .stButton > button {
    #         content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='9 18 15 12 9 6'%3E%3C/polyline%3E%3C/svg%3E");
    #         background-color: #9FADCC;
    #         color: white;
    #         padding: 16px 16px;
    #         font-size: 16px;
    #         border-radius: 45px;
    #         border: none;
    #         cursor: pointer;
    #         transition: background-color 0.3s ease;
    #     }
    #     .stButton > button:focus {
    #         background-color: #00ABD7;
    #     }

    #     .stButton{
    #         position: absolute;
    #         left:75vw;
    #         bottom: 3.25vh;

    #     }
    #     </style>
    # """


    # # Inject the custom CSS
    # st.markdown(button_style, unsafe_allow_html=True)

    # Inject the custom CSS
    st.markdown(button_style, unsafe_allow_html=True)


    # Subdomain brute force discovery
    def discover_subdomains(domain):
        found_subdomains = []
        for subdomain in COMMON_SUBDOMAINS:
            try:
                resolved = dns.resolver.resolve(f"{subdomain}.{domain}", 'A')
                found_subdomains.append(f"{subdomain}.{domain}")
            except (dns.resolver.NXDOMAIN, dns.resolver.Timeout):
                continue
        return found_subdomains

    # Original code starts here
    # Takes in user input
    with st.form(key='url_form', clear_on_submit=True):
        # Input for URL
        input_url = st.text_area("", placeholder="Enter the URL to test for vulnerabilities")
    
        # Submit button inside the form
        submit_button = st.form_submit_button("Run Scan")

    # if (input_url or submit_button) and not input_url.startswith(('http://', 'https://')):
    #     input_url = 'https://' + input_url
        
    if submit_button and input_url != "":
        try:
            st.info("Running vulnerability scan... Results will update in real-time.")
            
            # Perform the scan
            scan_results, highest_threat_level = perform_vulnerability_scan(input_url)
            
            # Display results
            if scan_results:
                df = pd.DataFrame(scan_results)
                st.table(df)
                st.success(f"Scan completed! Highest threat level detected: {highest_threat_level}")
        except Exception as e:
            st.error(f"Failed to process URL: {str(e)}")
            st.info("Please ensure Chrome is installed and properly configured.")
    elif submit_button:
        st.warning("Please enter a valid URL.")

    # Username and password brute-force
    usernames = ['user1', 'user2', 'admin']
    passwords = ['password1', 'password2', '123456']
    login_url = 'https://example.com/login'  # Replace with the actual URL

    # Session object to maintain the session cookies
    session = requests.Session()

    # Loop through the username and password pairs
    for username in usernames:
        for password in passwords:
            # Prepare the login data
            login_data = {
                'username': username,
                'password': password
            }

            response = session.post(login_url, data=login_data)
            if 'Login Successful' in response.text:
                print(f"Successful login - Username: {username}, Password: {password}")
                break

    session.close()

if selected == "MITRE Chatbot":
    # run_mitre(report)  --  att&ck and cwe report
    # run_mitre(report)  --  att&ck and cwe report
    processThreatsScenario("vulnerability_new.txt")
    # print("Process Threat Completed...")
    # st.empty()
    
#     report_data = {s
#        "report_name": "MITRE 1 Report",
#        "data": [{"key": "value"}, {"key2": "value2"}]  # Ensure this is a list of dictionaries or simple data types
   #if regex(for i in report_folder: i has "attk") then put to report_data_1
   #if regex(for i in report_folder: i has "cwe")  then put to report_data_2
   #report_data_1 = /report_folder/x.json
   #report_data_2 = /report_folder/y.json
    padl, mitre, padr = st.columns([0.05, 0.9, 0.05 ])

    # with mitreleft:
    remediation = "As the target is lacking this header, older browsers will be prone to Reflected XSS attacks. With this vulnerability the attacker will be able to perform a MiTM attack and thus compromising the confidentiality factor. The email address of the administrator and other information (address, phone, etc) is available publicly."
    #     report_options = st.selectbox("Select Report to Download", ["MITRE 1 Report", "MITRE 2 Report"])
    #     if report_options == "MITRE 1 Report":
    #         report_json = json.dumps(report_data)
    #         st.download_button("Download Report", report_json_1, "mitre_1_attk_report.json", "application/json")
    #         # delete from report_folder
    #     elif report_options == "MITRE 2 Report": # Replace with actual report data
    #         report_json = json.dumps(report_data)
    #         st.download_button("Download Report", report_json_2, "mitre_2_cwe_report.json", "application/json")
    #         # delete from report_folder

    chatbot_style = """
    <style>
        .chat-message {
            margin: 10px 0; /* Space between messages */
            padding: 10px; /* Padding for messages */
            border-radius: 10px; /* Rounded corners for messages */
        }
        .user-message {
            text-align: right; /* Align user messages to the right */
        }
        .assistant-message {
            text-align: left; /* Align assistant messages to the left */
        }
        .chat-input {
            margin-top: 20px; /* Space above input */
            display: flex; /* Flexbox for input and button */
        }

        .remediationstyle{
        font-family: 'Inter', sans-serif;
        text-align: left;
        font-size: 16px !important;
        color: #767676; 
        transition: opacity 3s ease-in-out;
        margin-top : 2vh;
        }
        
        
        .st-c0 {
            min-height: 70px;
            margin-bottom: 10px !important;
        }

        h2 {
            font-family: 'Inter', sans-serif;
            margin-top: -3vh;
        }

        /* Ensure all regular text and markdown text is black */
        p, .markdown-text-container {{
            color: black;
        }}
        /* Remove black background from text area container */
        .stTextArea {{
            margin-top :0px !important;
            background-color: transparent !important;
        }}
        
        /* Remove any additional container styling */
        .element-container {{
            background-color: transparent !important;
        }}

        /* Remove default streamlit container backgrounds */
        [data-testid="stForm"] {{
            background-color: transparent !important;
        }}
        

    </style>
    """

    
    svg_btn = get_base64_encoded_image("submit.svg")

    # button_style = """
    #     <style>
    #     .stButton > button {
    #         content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='9 18 15 12 9 6'%3E%3C/polyline%3E%3C/svg%3E");
    #         background-color: #9FADCC;
    #         color: white;
    #         padding: 16px 16px;
    #         font-size: 16px;
    #         border-radius: 45px;
    #         border: none;
    #         cursor: pointer;
    #         transition: background-color 0.3s ease;
    #     }
    #     .stButton > button:focus {
    #         background-color: #00ABD7;
    #     }

    #     .stButton{
    #         position: absolute;
    #         left:75vw;
    #         bottom: 3.25vh;

    #     }
    #     </style>
    # """


    # # Inject the custom CSS
    # st.markdown(button_style, unsafe_allow_html=True)
    # Inject the custom CSS into the app
    st.markdown(chatbot_style, unsafe_allow_html=True)

    # Update the chatbot area layout
    with mitre:
        try:
            user_avatar_base64 = get_base64_encoded_image("user_avatar.png")
            assistant_avatar_base64 = get_base64_encoded_image("assistant_avatar.png")
    
            # If either avatar fails to load, use default values
            if not user_avatar_base64 or not assistant_avatar_base64:
                # Provide default avatar base64 strings
                user_avatar_base64 = "default_user_avatar_base64_string"
                assistant_avatar_base64 = "default_assistant_avatar_base64_string"
                st.warning("Using default avatars as image files couldn't be loaded")
        except Exception as e:
            st.error(f"Error loading avatars: {str(e)}")
            # Provide default avatar base64 strings
            user_avatar_base64 = "default_user_avatar_base64_string"
            assistant_avatar_base64 = "default_assistant_avatar_base64_string"
        st.markdown("""
                <style>
                .blue-btn{
                    color : #4B4B4B;
                    background-color : #63D3F1;
                    padding : 8px;
                    border-radius:12px;
                    width: 19vw;
                    font-weight : 600;
                    font-size: 20px;
                    align-items:center;
                    text-align:center;
                    margin-top : -8vh;
                }
                .gradient-text{
                            font-family: 'Inter', sans-serif;
                            letter-spacing: -0.1rem;
                            font-size:3rem;
                            font-weight: 600;
                            background: linear-gradient(to right, #000, #00ABD7);
                            -webkit-background-clip: text;
                            -webkit-text-fill-color: transparent;
                        }
                .chat-container{
                        max-height: 80vh;
                        overflow-y: auto;
                        display: flex;
                        flex-direction: column;
                        }
                    
                h1{
                        font-family: 'Inter', sans-serif;
                        letter-spacing: -0.1rem;
                        font-size:3rem;
                        font-weight: 600;
                        color:black;
                        text-align :center;
                    }
                """, unsafe_allow_html = True)
        avatar_style = f"""
            <style>
        .user-message {{
            position: relative;
            margin-right: 100px;  /* Make space for avatar */
        }}
        
        .assistant-message {{
            position: relative;
            padding-left: 100px;  /* Make space for avatar */
        }}

        .user-message::after {{
            content: '';
            position: absolute;
            right: -50px;  /* Moved inside the message container */
            top: 50%;
            transform: translateY(-50%);
            width: 35px;
            height: 35px;
            background-image: url("data:image/png;base64,{user_avatar_base64}");
            background-size: cover;
            background-position: center;
            border-radius: 50%;
        }}

        .assistant-message::before {{
            content: '';
            position: absolute;
            left: -50px;  /* Moved inside the message container */
            top: 50%;
            transform: translateY(-50%);
            width: 35px;
            height: 35px;
            background-image: url("data:image/png;base64,{assistant_avatar_base64}");
            background-size: cover;
            background-position: center;
            border-radius: 50%;
            z-index: 100;
            }}
        .bluebar{{
            margin: 3vh auto;
            height: 4px;
            background-color: rgba(147, 196, 244, 0.3);
            width: 1000px;
            border-radius: 16px;
        }}

        </style>
"""
        st.markdown(avatar_style, unsafe_allow_html=True)
    

        st.markdown(f"""
            <div class ="blue-btn">Vulnerabililty Remediations</div>
            <div class = "remediationstyle" >{remediation}</div>

            <div style = "padding-top : 30px; color : #000; font-weight:medium; ">Select Report to Download</div>
                
        """, unsafe_allow_html=True)
        # report_data_1 = {"key": "value1", "key2": "value2"}
        # report_data_2 = {"key": "value3", "key4": "value4"}

        # # Convert reports to JSON format
        # report_json_1 = json.dumps(report_data_1, indent=4)
        # report_json_2 = json.dumps(report_data_2, indent=4)

        # Layout for displaying both download buttons side by side
        col1, col2, colpad = st.columns([1.2,1.2,3.6])
        def find_report_folder():
            # Define the fixed part of the path
            target_folder = os.path.join("Web-Vulnerability-Scanner", "Mitre-Att&ck", "ReportFolder")
            
            # Start searching from the current working directory
            for root, dirs, files in os.walk("."):
                # Check if the target folder exists in the current path
                if target_folder in os.path.join(root, target_folder):
                    full_path = os.path.join(root, target_folder)
                    if os.path.exists(full_path):
                        return os.path.abspath(full_path)
            
            return None  # Return None if the folder is not found

        # Find the report folder
        # report_folder = find_report_folder()
        report_folder = "/Users/apple/Desktop/Web-Vulnerability-Scanner/Mitre-Att&ck/src/ReportFolder"
        def delete_folder_contents(folder_path):
            shutil.rmtree(folder_path)
            os.makedirs(folder_path)
        if report_folder:
            report_file_1 = None
            
            # Iterate through files in the report folder
            for file_name in os.listdir(report_folder):
                if re.search(r'Atk', file_name, re.IGNORECASE) and file_name.endswith(".json"):
                    report_file_1 = os.path.join(report_folder, file_name)
                    print(f"Found report file: {report_file_1}")
                    break

            if report_file_1:
                # Read the JSON file content
                with open(report_file_1, "r") as file:
                    report_data_1 = file.read()

                # Create a download button in Streamlit
                with st.container():
                    if st.download_button(
                        label="MITRE ATT&CK Report",
                        data=report_data_1,
                        file_name="mitre_attk_report.json",
                        mime="application/json",
                    ):
                        delete_folder_contents(report_folder)
            else:
                st.warning("No matching report file found in the ReportFolder.")
               
        else:
            st.error("Report folder not found.")


        st.markdown(f"""
            <div class = "bluebar" ></div>
                
        """, unsafe_allow_html=True)
        # Initialize Groq client
        client = Groq(
            api_key="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",  # Ensure your API key is set in the environment
        )
        model = client.models.retrieve("llama-3.1-8b-instant")

        # Set the default model in session state
        if "groq_model" not in st.session_state:
            st.session_state["groq_model"] = "llama-3.1-8b-instant"

        # Initialize chat history
        if "messages" not in st.session_state:
                st.session_state.messages = [
                {"role": "assistant", "content": f"Here's what I found about the vulnerabilities: {remediation}\n\nHow can I help you understand this better?"}
            ]

        # CSS for the chat UI
        st.markdown("""
            <style>
            .chat-container {
                max-width: 90vw;
                margin: 0 auto;
                background-color: transparent;
            }
            .gradient-text {
                background: linear-gradient(to right, #000, #00ABD7);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
            }
            .chat-messages {
                height: 50vh;
                overflow-y: auto;
                border: 0px solid #ddd;
                border-radius: 8px;
                padding: 10px;
                background: transparent;
            }
            .chat-message {
                display: inline-block;
                max-width: 70%;
                margin: 10px 100px; /* Add horizontal margin to prevent overflow */
                padding: 10px 100px; /* Increase padding to make room for avatars */
                border-radius: 8px;
                border: 1px solid #ddd;
                word-wrap: break-word;
                clear: both;
                width: auto;
                background-color: white;
                position: relative;  /* For avatar positioning */
            }
            .user-message {
                float: right;
                right:50px;
                border-right: 5px solid black;
                margin-right: 100px;  /* Space for avatar */
            }
            .assistant-message {
                float: left;
                left:50px;
                border-left: 5px solid black;
                margin-left: 100px;  /* Space for avatar */
            }
            .avatar {
                width: 35px;
                height: 35px;
                border-radius: 50%;
                bottom: 10px;
            }
            
            </style>
        """, unsafe_allow_html=True)

        # Display the chat header and description
        st.markdown("""
            <div class="chat-container">
                <h1>How can we <span class="gradient-text">assist</span> you on this?</h1>
                <div style="text-align:center; width: 45vw; margin: auto; padding-bottom: 10px;" class = "remediationstyle">Navigate the complexities of vulnerability remediation with ease. We are here to provide precise solutions, tailored recommendations. Ask your questions and take a step closer to a safer digital environment.</div>
            </div>
        """, unsafe_allow_html=True)

        # Generate chat messages dynamically with avatars
        chat_messages_html = ""
        for message in st.session_state.messages:
            if message["role"] == "user":
                chat_messages_html += f'<div class="chat-message user-message">{message["content"]}</div>'
            else:
                chat_messages_html += f'<div class="chat-message assistant-message">{message["content"]}</div>'

        # Display the chat container with message
        st.markdown(f"""
            <div class="chat-container">
                <div class="chat-messages">
                    {chat_messages_html}
                </div>
            </div>
            """, unsafe_allow_html=True)

            # Create placeholder for latest messages
            # placeholder = st.empty()
            
            # If there are messages, update the placeholder with the latest one
            # if st.session_state.messages:
            #     last_message = st.session_state.messages[-1]
                
        # Add custom CSS for the chat input and button
        chat_input_style = """
        <style>
            /* Style for the form container */
            .stTextInput > div > div > input {
                background-color: transparent !important;
                border-radius: 45px;
                color: black !important;
            }

            /* Ensure ALL markdown text is black */
            .css-10trblm, .css-183lzff, .element-container div {
                color: black;
            }

            /* Make sure list items are also black */
            li {
                color: black !important;
            }
            
            [data-testid="stTextArea"] > div {
                background-color: rgba(140, 140, 140, 0.24) !important;
                width: 900px;
                min-height: 50px !important;
                max-height: 65px !important;
                margin: auto;
                border-radius: 45px;
                border: none !important;
            }
            [data-testid="InputInstructions"] {
                display: none !important;
                background-color: transparent !important;
            }

            [data-testid="stTextArea"] > div > div {
                background-color: transparent !important;
                border: none !important;
                padding: 8px 12px !important;
            }
             .st-c0 {
            min-height: 70px;
                margin-bottom: 10px !important;
            }

            /* Style the text area */
            .stTextArea textarea {
                background-color: transparent !important;
                border-radius: 45px;
                color: black !important;
                min-height: 40px !important;  // Set minimum height for textarea
    padding: 8px 12px !important;  // Add padding
                margin-top: 5px !important;   // Add some top margin
                resize: none !important;
            }

            /* Ensure all regular text and markdown text is black */
            p, .markdown-text-container {
                color: black;
            }

            /* Remove black background from text area container */
            .stTextArea {
                background-color: transparent !important;
            }
            
            /* Remove any additional container styling */
            .element-container {
                background-color: transparent !important;
            }

            /* Remove default streamlit container backgrounds */
            [data-testid="stForm"] {
                background-color: transparent !important;
            }
        </style>"""

        # Inject the custom CSS
        st.markdown(chat_input_style, unsafe_allow_html=True)

        button_style = """
            <style>
            [data-testid="stFormSubmitButton"] > button {
                content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='9 18 15 12 9 6'%3E%3C/polyline%3E%3C/svg%3E");
                background-color: #000;
                color: white;
                padding: 16px 16px;
                font-size: 16px;
                border-radius: 45px;
                border: none;
                cursor: pointer;
                transition: background-color 0.3s ease;
            }
            [data-testid="stFormSubmitButton"] > button:focus {
                background-color: #00ABD7;
            }

            [data-testid="stFormSubmitButton"]{
                position: relative;
                margin-left: 839px;
            
                bottom: 76px;
            
            }
            [data-testid="stForm"] {
                background-color: transparent !important;
                padding: 0 !important;
                margin: auto !important;
                display: flex;
                justify-content: center;
                border:none !important;
                margin-bottom: 10px !important;
            }
            [data-testid="stMain"] {
                margin-bottom: -220px !important;
            }

            </style>
        """


        # Inject the custom CSS
        st.markdown(button_style, unsafe_allow_html=True)

        # Create the chat form
        with st.form(key='chat_form', clear_on_submit=True):
            # Input for user prompt
            prompt = st.text_area("", placeholder="Type your query here...")
            
            # Submit button inside the form
            submit_button_1 = st.form_submit_button("Send")

        # Send button to trigger the assistant response
        if submit_button_ and prompt:
            # Add the user message to the session state
            st.session_state.messages.append({"role": "user", "content": prompt})

            try:
                chat_completion = client.chat.completions.create(
                    messages=[{"role": "user", "content": prompt}],
                        model=st.session_state["groq_model"],
                        stream=False,
                )
                content = chat_completion.choices[0].message.content
                if content:
                    st.session_state.messages.append({"role": "assistant", "content": content})
                # Add the assistant's response to the session state
                st.rerun()
            except Exception as e:
                st.error(f"Error: {str(e)}")

